<?php
/**
 * WordPress Breakdown with Examples and Real-Life Use Cases
 * --------------------------------------------------------
 * Purpose:
 * This file is a learning/reference document. It is NOT intended to be installed
 * as a real WordPress plugin or theme file.
 *
 * It combines comments, PHP snippets, pseudo-code, SQL examples, HTML, CSS,
 * JavaScript, and WP-CLI examples to explain common WordPress concepts in a
 * practical way.
 *
 * How to use this file:
 * - Read it as study notes.
 * - Copy individual snippets into a theme/plugin only after adapting them.
 * - Do not upload this entire file to production as-is.
 */

/* ========================================================================== */
/* 1. WORDPRESS BASICS                                                        */
/* ========================================================================== */

/**
 * 1.1 What is WordPress?
 *
 * WordPress is a CMS (Content Management System). It allows users and teams to
 * create, edit, organize, and publish website content without manually editing
 * HTML files every time.
 *
 * Real-life use case:
 * A cake shop wants a website with:
 * - Home page
 * - Menu/products
 * - Contact page
 * - Blog/news
 * - Online orders using WooCommerce
 *
 * Instead of building a full custom admin dashboard from scratch, WordPress gives
 * the client an admin panel where they can edit pages, products, images, and orders.
 */

/**
 * 1.2 PHP in WordPress
 *
 * WordPress is written mainly in PHP. PHP runs on the server and generates the
 * HTML that the browser receives.
 *
 * Real-life use case:
 * When a visitor opens a blog post, WordPress uses PHP to:
 * 1. Receive the request.
 * 2. Ask the database for the post data.
 * 3. Load the active theme template.
 * 4. Print the final HTML.
 */

// Example: basic WordPress template tags usually used inside The Loop.
// These functions would print the current post title and content.
/*
the_title();
the_content();
*/

/**
 * Example HTML generated by PHP after WordPress renders a page:
 *
 * <article>
 *   <h1>How to Choose the Right Cake</h1>
 *   <div class="entry-content">
 *     <p>This is the post content stored in the database.</p>
 *   </div>
 * </article>
 */

/**
 * 1.3 SQL / Database
 *
 * WordPress normally uses MySQL or MariaDB.
 * The database stores most site data:
 * - Pages
 * - Posts
 * - Users
 * - Menus
 * - Plugin settings
 * - Theme settings
 * - WooCommerce orders
 * - Contact form entries, depending on the plugin
 *
 * Real-life use case:
 * A client edits the About page from wp-admin. The page content is not usually
 * saved in a PHP file. It is stored in the database, mainly in wp_posts.
 */

// Example SQL query for learning purposes only.
// This gets the latest 5 published blog posts.
/*
SELECT ID, post_title, post_date
FROM wp_posts
WHERE post_type = 'post'
  AND post_status = 'publish'
ORDER BY post_date DESC
LIMIT 5;
*/

// Example: getting a WordPress option from PHP.
/*
$site_name = get_option('blogname');
echo esc_html($site_name);
*/


/* ========================================================================== */
/* 2. WORDPRESS MAIN CONCEPTS                                                 */
/* ========================================================================== */

/**
 * 2.1 Themes
 *
 * A theme controls the visual appearance and layout of the website.
 * It usually includes PHP templates, CSS files, JavaScript files, images, and
 * theme configuration.
 *
 * Real-life use case:
 * A law firm wants a professional website with:
 * - Header
 * - Navigation menu
 * - Hero section
 * - Practice areas
 * - Attorney profiles
 * - Contact form
 * - Footer
 *
 * A theme provides the base design and structure.
 *
 * Common theme files:
 * - style.css
 * - functions.php
 * - header.php
 * - footer.php
 * - index.php
 * - single.php
 * - page.php
 * - archive.php
 */

/**
 * 2.2 Plugins
 *
 * A plugin adds or modifies functionality without editing WordPress core.
 *
 * Real-life use cases:
 * - Add a contact form: Gravity Forms, WPForms, Contact Form 7.
 * - Add SEO tools: Yoast SEO, Rank Math.
 * - Add e-commerce: WooCommerce.
 * - Add security: Wordfence.
 * - Add custom fields: Advanced Custom Fields (ACF).
 * - Add caching/performance: WP Rocket, LiteSpeed Cache.
 */

// Example: this is the kind of plugin header used by WordPress.
// Do not activate this full file as a plugin. This is only an example.
/*
Plugin Name: Custom Site Helpers
Description: Adds small custom functionality for a specific client website.
Version: 1.0.0
Author: Your Name
*/

/**
 * 2.3 Widgets
 *
 * Widgets are small reusable blocks of content usually placed in sidebars,
 * footers, or widget-ready areas.
 *
 * Real-life use case:
 * A blog sidebar may include:
 * - Search bar
 * - Recent posts
 * - Categories
 * - Newsletter signup
 * - Social media links
 */

/**
 * Example widget-like area in a classic theme template:
 *
 * if ( is_active_sidebar('blog-sidebar') ) {
 *     dynamic_sidebar('blog-sidebar');
 * }
 */


/* ========================================================================== */
/* 3. INSTALLING WORDPRESS                                                    */
/* ========================================================================== */

/**
 * 3.1 Download WordPress
 *
 * Real-life use case:
 * You need to manually install WordPress on a cPanel/Hostinger/GoDaddy server.
 * You download WordPress, upload the files, create a database, and run the setup.
 */

/**
 * 3.2 Create a Database
 *
 * Example database information:
 * - Database name: client_site_db
 * - Database user: client_site_user
 * - Password: strong_password_here
 * - Host: localhost
 *
 * Real-life use case:
 * During the WordPress installer, you enter these credentials so WordPress can
 * save and retrieve site content.
 */

// Example wp-config.php values. Do not use these exact credentials.
/*
define('DB_NAME', 'client_site_db');
define('DB_USER', 'client_site_user');
define('DB_PASSWORD', 'strong_password_here');
define('DB_HOST', 'localhost');
*/

/**
 * 3.3 Upload WordPress Files
 *
 * Common server folders:
 * - public_html/
 * - public_html/clientdomain.com/
 * - htdocs/
 *
 * Real-life use case:
 * You upload WordPress files through File Manager, FTP, SFTP, or SSH.
 */

// Example command-line upload concept, not a full real command.
/*
scp -r wordpress/* user@server:/home/user/public_html/
*/

/**
 * 3.4 Run Installation Script
 *
 * Real-life use case:
 * After files and database are ready, you visit the domain in a browser and
 * WordPress asks for site title, admin username, password, and email.
 */

/**
 * 3.5 LocalWP
 *
 * LocalWP is a friendly local WordPress development app.
 *
 * Real-life use case:
 * Before updating Elementor or WooCommerce on production, you clone the site
 * locally and test the update in a safe environment.
 */

/**
 * 3.6 XAMPP
 *
 * XAMPP provides Apache, PHP, and MariaDB/MySQL locally.
 *
 * Real-life use case:
 * A beginner developer wants to practice WordPress locally at:
 * http://localhost/my-wordpress-site
 */

/**
 * 3.7 VVV
 *
 * VVV is a developer-focused local WordPress environment using Vagrant.
 *
 * Real-life use case:
 * Useful for WordPress core development, plugin testing, and consistent team
 * environments.
 */

/**
 * 3.8 Docker for WordPress
 *
 * Docker runs services in containers.
 *
 * Real-life use case:
 * A team wants the same PHP, MySQL, and WordPress versions for every developer.
 */

// Example docker-compose.yml structure, included as a comment.
/*
version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
*/


/* ========================================================================== */
/* 4. THEMES, THEME TYPES, AND SITE STRUCTURE                                  */
/* ========================================================================== */

/**
 * 4.1 Classic Themes
 *
 * Classic themes rely heavily on PHP templates.
 *
 * Real-life use case:
 * A client has an older WordPress site. To edit the blog post layout, you may
 * need to edit single.php in a child theme.
 */

// Example: simple single.php structure.
/*
get_header();

if ( have_posts() ) :
    while ( have_posts() ) :
        the_post();
        ?>
        <main class="single-post">
            <h1><?php the_title(); ?></h1>
            <div><?php the_content(); ?></div>
        </main>
        <?php
    endwhile;
endif;

get_footer();
*/

/**
 * 4.2 Block Themes
 *
 * Block themes use blocks and the Site Editor to control templates, header,
 * footer, and layouts.
 *
 * Real-life use case:
 * A small business owner wants to edit the header and footer visually from
 * Appearance > Editor without touching PHP files.
 */

/**
 * 4.3 Child Themes
 *
 * A child theme inherits from a parent theme and lets you customize safely.
 *
 * Real-life use case:
 * A client uses Astra. You need custom WooCommerce CSS. You add it to an Astra
 * child theme so the parent theme can still be updated.
 */

// Example child theme style.css header.
/*
Theme Name: Astra Child
Template: astra
Version: 1.0.0
*/

// Example child theme functions.php enqueueing parent/child styles.
/*
add_action('wp_enqueue_scripts', 'astra_child_enqueue_styles');
function astra_child_enqueue_styles() {
    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
    wp_enqueue_style('child-style', get_stylesheet_uri(), array('parent-style'), '1.0.0');
}
*/

/**
 * 4.4 Hybrid Themes
 *
 * Hybrid themes combine PHP templates with block editor features.
 *
 * Real-life use case:
 * The site structure is still controlled by PHP, but page content is managed
 * with Gutenberg blocks.
 */

/**
 * 4.5 Third-Party Themes
 *
 * Third-party themes are made by external companies or developers.
 *
 * Real-life use case:
 * A client has a limited budget and needs a fast launch. You use Kadence,
 * GeneratePress, Astra, Divi, Avada, or a ThemeForest theme as a base.
 *
 * Practical warning:
 * Some multipurpose themes include many features, which can impact performance.
 * Always review scripts, CSS, plugins, and page builder dependencies.
 */

/**
 * 4.6 WordPress File Structure
 *
 * Important folders:
 * - wp-admin/       WordPress admin files.
 * - wp-includes/    WordPress core files.
 * - wp-content/     Themes, plugins, uploads, and custom content.
 *
 * Most developer work happens in:
 * - wp-content/themes/
 * - wp-content/plugins/
 * - wp-content/uploads/
 *
 * Real-life use cases:
 * - Plugin fatal error: rename the plugin folder to disable it.
 * - Missing images: check wp-content/uploads/.
 * - Theme customization: check active theme or child theme folder.
 */

// Example emergency plugin disable via folder rename.
/*
wp-content/plugins/problem-plugin/
wp-content/plugins/problem-plugin-disabled/
*/

/**
 * 4.7 Page Editors
 *
 * Page editors allow visual page building.
 *
 * Common editors/builders:
 * - Gutenberg
 * - Elementor
 * - Beaver Builder
 * - Divi
 * - WPBakery
 *
 * Real-life use case:
 * A marketing team wants to edit landing page content without asking a developer
 * every time. Elementor or Gutenberg can allow controlled visual editing.
 */


/* ========================================================================== */
/* 5. HOOKS: ACTIONS AND FILTERS                                               */
/* ========================================================================== */

/**
 * 5.1 Hooks
 *
 * Hooks allow developers to modify WordPress behavior without editing WordPress
 * core files.
 *
 * Two main types:
 * - Actions: do something at a specific moment.
 * - Filters: modify data before it is displayed or saved.
 */

/**
 * 5.2 Actions
 *
 * Real-life use case:
 * Add a custom script to the footer, register a custom post type, add admin
 * menu pages, or run setup logic.
 */

// Example action: add custom code to the footer.
/*
add_action('wp_footer', 'my_custom_footer_marker');
function my_custom_footer_marker() {
    echo '<!-- Custom footer marker for QA or tracking -->';
}
*/

// Example action: enqueue scripts and styles properly.
/*
add_action('wp_enqueue_scripts', 'my_theme_assets');
function my_theme_assets() {
    wp_enqueue_style(
        'my-theme-style',
        get_stylesheet_uri(),
        array(),
        '1.0.0'
    );

    wp_enqueue_script(
        'my-theme-main-js',
        get_template_directory_uri() . '/assets/js/main.js',
        array('jquery'),
        '1.0.0',
        true
    );
}
*/

// Example action: register a custom post type on init.
/*
add_action('init', 'register_case_study_post_type');
function register_case_study_post_type() {
    register_post_type('case_study', array(
        'label' => 'Case Studies',
        'public' => true,
        'has_archive' => true,
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite' => array('slug' => 'case-studies'),
    ));
}
*/

/**
 * 5.3 Filters
 *
 * Filters modify data and return it.
 *
 * Real-life use case:
 * Add a CTA after blog posts, modify titles, change excerpt length, modify
 * WooCommerce button text, or adjust form output.
 */

// Example filter: add CTA after each single blog post.
/*
add_filter('the_content', 'add_cta_after_blog_post');
function add_cta_after_blog_post($content) {
    if ( is_single() && get_post_type() === 'post' ) {
        $content .= '<div class="post-cta">Need help with your website? Contact us today.</div>';
    }

    return $content;
}
*/

// Example filter: change excerpt length.
/*
add_filter('excerpt_length', 'custom_excerpt_length');
function custom_excerpt_length($length) {
    return 25;
}
*/

/**
 * 5.4 Custom Hooks
 *
 * Developers can create their own hooks inside themes or plugins.
 *
 * Real-life use case:
 * You build a custom plugin and want to let future developers inject extra logic
 * after a custom form is submitted.
 */

// Plugin/theme code creates the action.
/*
do_action('my_plugin_after_form_submit', $submission_id);
*/

// Another developer can hook into it.
/*
add_action('my_plugin_after_form_submit', 'send_internal_notification');
function send_internal_notification($submission_id) {
    // Send email or log the submission.
}
*/


/* ========================================================================== */
/* 6. THE LOOP                                                                 */
/* ========================================================================== */

/**
 * 6.1 The Loop
 *
 * The Loop is how WordPress displays posts/pages from the database.
 *
 * Real-life use case:
 * A blog archive page displays multiple posts. For each post, WordPress prints:
 * - Title
 * - Date
 * - Featured image
 * - Excerpt
 * - Read more link
 */

// Basic Loop example.
/*
if ( have_posts() ) :
    while ( have_posts() ) :
        the_post();
        ?>
        <article id="post-<?php the_ID(); ?>">
            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div class="excerpt"><?php the_excerpt(); ?></div>
        </article>
        <?php
    endwhile;
else :
    echo '<p>No posts found.</p>';
endif;
*/

// Custom WP_Query example: show 6 case studies.
/*
$case_studies = new WP_Query(array(
    'post_type' => 'case_study',
    'posts_per_page' => 6,
));

if ( $case_studies->have_posts() ) :
    while ( $case_studies->have_posts() ) :
        $case_studies->the_post();
        ?>
        <article class="case-study-card">
            <?php the_post_thumbnail('medium'); ?>
            <h3><?php the_title(); ?></h3>
            <?php the_excerpt(); ?>
        </article>
        <?php
    endwhile;
    wp_reset_postdata();
endif;
*/


/* ========================================================================== */
/* 7. SHORTCODES                                                               */
/* ========================================================================== */

/**
 * 7.1 Shortcodes
 *
 * Shortcodes let users insert dynamic content into posts/pages using a simple
 * bracket syntax.
 *
 * Real-life use cases:
 * - Insert a contact form: [gravityform id="3"]
 * - Insert a gallery: [gallery]
 * - Insert current year in footer: [current_year]
 */

// Example custom shortcode: current year.
/*
add_shortcode('current_year', 'show_current_year_shortcode');
function show_current_year_shortcode() {
    return date('Y');
}
*/

/**
 * User can write this in the editor:
 * © [current_year] My Company. All rights reserved.
 *
 * Output:
 * © 2026 My Company. All rights reserved.
 */

// Example shortcode with attributes.
/*
add_shortcode('button', 'custom_button_shortcode');
function custom_button_shortcode($atts) {
    $atts = shortcode_atts(array(
        'url' => '#',
        'label' => 'Click here',
    ), $atts);

    return '<a class="btn" href="' . esc_url($atts['url']) . '">' . esc_html($atts['label']) . '</a>';
}
*/

/**
 * User can write:
 * [button url="/contact" label="Contact us"]
 */


/* ========================================================================== */
/* 8. STYLE AND SCRIPT ENQUEUEING                                              */
/* ========================================================================== */

/**
 * 8.1 Enqueueing
 *
 * Enqueueing is the correct WordPress way to load CSS and JavaScript.
 *
 * Bad approach:
 * Hardcoding scripts directly in header.php or footer.php.
 *
 * Better approach:
 * Use wp_enqueue_style() and wp_enqueue_script().
 *
 * Real-life use case:
 * You need to add custom JavaScript for a mobile menu and custom CSS for a
 * landing page. Enqueueing prevents duplicate loading and helps manage dependencies.
 */

// Example enqueue function.
/*
add_action('wp_enqueue_scripts', 'site_enqueue_assets');
function site_enqueue_assets() {
    wp_enqueue_style(
        'site-main-css',
        get_template_directory_uri() . '/assets/css/main.css',
        array(),
        '1.0.0'
    );

    wp_enqueue_script(
        'site-main-js',
        get_template_directory_uri() . '/assets/js/main.js',
        array(),
        '1.0.0',
        true
    );
}
*/

// Example conditional enqueue: only load CSS on contact page.
/*
add_action('wp_enqueue_scripts', 'contact_page_assets');
function contact_page_assets() {
    if ( is_page('contact') ) {
        wp_enqueue_style(
            'contact-page-css',
            get_template_directory_uri() . '/assets/css/contact.css',
            array(),
            '1.0.0'
        );
    }
}
*/

// Example JavaScript file content for /assets/js/main.js.
/*
document.addEventListener('DOMContentLoaded', function () {
  const menuButton = document.querySelector('.menu-toggle');
  const menu = document.querySelector('.main-menu');

  if (menuButton && menu) {
    menuButton.addEventListener('click', function () {
      menu.classList.toggle('is-open');
    });
  }
});
*/

// Example CSS file content for /assets/css/main.css.
/*
.main-menu {
  display: none;
}

.main-menu.is-open {
  display: block;
}

.btn {
  display: inline-block;
  padding: 12px 20px;
  text-decoration: none;
}
*/


/* ========================================================================== */
/* 9. CUSTOM POST TYPES                                                        */
/* ========================================================================== */

/**
 * 9.1 Custom Post Types
 *
 * Custom Post Types (CPTs) create structured content beyond posts and pages.
 *
 * Real-life examples:
 * - Agency website: Case Studies
 * - Real estate website: Properties
 * - Restaurant website: Menu Items
 * - Doctor website: Doctors
 * - School website: Courses
 * - Portfolio website: Projects
 * - Reviews section: Testimonials
 */

// Example: register Case Studies CPT.
/*
add_action('init', 'register_case_studies_cpt');
function register_case_studies_cpt() {
    register_post_type('case_study', array(
        'labels' => array(
            'name' => 'Case Studies',
            'singular_name' => 'Case Study',
            'add_new_item' => 'Add New Case Study',
            'edit_item' => 'Edit Case Study',
        ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-portfolio',
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite' => array('slug' => 'case-studies'),
        'show_in_rest' => true,
    ));
}
*/

/**
 * Example final URLs:
 * /case-studies/
 * /case-studies/client-name/
 */

/**
 * Real-life structure for an agency Case Study:
 * - Title: "How We Increased Leads by 130%"
 * - Featured image: Client logo or campaign image
 * - Content: Problem, solution, results
 * - Custom fields: Industry, services, result percentage, client testimonial
 */


/* ========================================================================== */
/* 10. TAXONOMIES                                                              */
/* ========================================================================== */

/**
 * 10.1 Taxonomies
 *
 * Taxonomies organize content into groups.
 *
 * Default taxonomies:
 * - Categories
 * - Tags
 *
 * Custom taxonomy examples:
 * - Properties: Location, Property Type, Price Range
 * - Case Studies: Industry, Service, Platform
 * - Courses: Level, Topic, Instructor
 */

// Example: register Industry taxonomy for Case Studies.
/*
add_action('init', 'register_case_study_industry_taxonomy');
function register_case_study_industry_taxonomy() {
    register_taxonomy('industry', array('case_study'), array(
        'labels' => array(
            'name' => 'Industries',
            'singular_name' => 'Industry',
        ),
        'public' => true,
        'hierarchical' => true,
        'rewrite' => array('slug' => 'case-studies/industry'),
        'show_in_rest' => true,
    ));
}
*/

/**
 * Example final taxonomy URLs:
 * /case-studies/industry/healthcare/
 * /case-studies/industry/ecommerce/
 */


/* ========================================================================== */
/* 11. CUSTOM FIELDS AND ACF                                                   */
/* ========================================================================== */

/**
 * 11.1 Custom Fields
 *
 * Custom fields store extra structured data for posts, pages, CPTs, and users.
 *
 * Real-life use case:
 * A Case Study needs fields that are not part of normal post content:
 * - Client name
 * - Industry
 * - Revenue increase
 * - Lead increase
 * - Testimonial
 *
 * ACF (Advanced Custom Fields) makes this easier through the admin UI.
 */

// Example ACF field usage in a template.
/*
$client_name = get_field('client_name');
$lead_increase = get_field('lead_increase');

if ( $client_name ) {
    echo '<p>Client: ' . esc_html($client_name) . '</p>';
}

if ( $lead_increase ) {
    echo '<p>Lead increase: ' . esc_html($lead_increase) . '%</p>';
}
*/

// Native WordPress custom field usage.
/*
$subtitle = get_post_meta(get_the_ID(), 'subtitle', true);
if ( $subtitle ) {
    echo '<p class="subtitle">' . esc_html($subtitle) . '</p>';
}
*/


/* ========================================================================== */
/* 12. WOOCOMMERCE EXAMPLES                                                    */
/* ========================================================================== */

/**
 * 12.1 WooCommerce
 *
 * WooCommerce adds e-commerce functionality to WordPress.
 *
 * Real-life use case:
 * A local cake shop wants to sell cookies online for local delivery/pickup.
 * WooCommerce can manage:
 * - Products
 * - Cart
 * - Checkout
 * - Orders
 * - Payment gateways
 * - Shipping/local pickup
 */

// Example: change Add to Cart button text.
/*
add_filter('woocommerce_product_single_add_to_cart_text', 'custom_add_to_cart_text');
function custom_add_to_cart_text() {
    return 'Order Now';
}
*/

// Example: show a message above checkout.
/*
add_action('woocommerce_before_checkout_form', 'local_delivery_checkout_notice');
function local_delivery_checkout_notice() {
    echo '<p class="checkout-notice">Local delivery is available only inside selected city areas.</p>';
}
*/


/* ========================================================================== */
/* 13. WORDPRESS SECURITY AND MAINTENANCE                                      */
/* ========================================================================== */

/**
 * 13.1 Updates and Backups
 *
 * Real-life use case:
 * Before updating Elementor, WooCommerce, or a theme, you should:
 * 1. Confirm there is a recent backup.
 * 2. Test on staging if possible.
 * 3. Apply updates.
 * 4. Test key pages and forms.
 * 5. Clear cache.
 */

/**
 * 13.2 Security Plugins
 *
 * Real-life use case:
 * A site receives an unauthorized admin user alert. You may:
 * - Remove unknown users.
 * - Change admin passwords.
 * - Install/check Wordfence or another security plugin.
 * - Review recently modified files.
 * - Check hosting logs.
 * - Update outdated plugins/themes.
 */

// Example: disable file editing from wp-admin in wp-config.php.
/*
define('DISALLOW_FILE_EDIT', true);
*/

// Example: force SSL admin in wp-config.php.
/*
define('FORCE_SSL_ADMIN', true);
*/


/* ========================================================================== */
/* 14. PERFORMANCE AND CACHE                                                   */
/* ========================================================================== */

/**
 * 14.1 Caching
 *
 * Caching stores generated pages/assets so the server does not need to rebuild
 * everything on every request.
 *
 * Real-life use case:
 * A marketing site loads slowly because every request triggers many PHP/database
 * operations. A cache plugin or host-level cache can serve faster HTML.
 *
 * Common cache layers:
 * - Browser cache
 * - Plugin cache
 * - Host/server cache
 * - CDN cache
 * - Object cache
 */

/**
 * 14.2 Performance Practical Checks
 *
 * Real-life use cases:
 * - Clear cache after CSS changes do not appear.
 * - Regenerate Elementor CSS if frontend styles are broken.
 * - Check if JavaScript optimization delays important clicks.
 * - Review image sizes if pages are heavy.
 */

// Example WP-CLI commands for maintenance.
/*
wp cache flush
wp transient delete --all
wp plugin list
wp theme list
wp option get blogname
*/


/* ========================================================================== */
/* 15. REST API AND AJAX                                                       */
/* ========================================================================== */

/**
 * 15.1 REST API
 *
 * WordPress includes a REST API that can expose content as JSON.
 *
 * Real-life use case:
 * A JavaScript frontend needs to fetch the latest blog posts from WordPress.
 * It can request:
 * /wp-json/wp/v2/posts
 */

// Example JavaScript fetch request.
/*
fetch('/wp-json/wp/v2/posts?per_page=3')
  .then(response => response.json())
  .then(posts => {
    posts.forEach(post => {
      console.log(post.title.rendered);
    });
  });
*/

// Example custom REST endpoint.
/*
add_action('rest_api_init', function () {
    register_rest_route('site/v1', '/status', array(
        'methods' => 'GET',
        'callback' => function () {
            return array(
                'status' => 'ok',
                'site' => get_bloginfo('name'),
            );
        },
        'permission_callback' => '__return_true',
    ));
});
*/

/**
 * 15.2 AJAX
 *
 * AJAX allows frontend interactions without a full page reload.
 *
 * Real-life use case:
 * A "Load More" button loads more case studies without refreshing the page.
 */

// PHP AJAX handler example.
/*
add_action('wp_ajax_load_more_posts', 'load_more_posts');
add_action('wp_ajax_nopriv_load_more_posts', 'load_more_posts');

function load_more_posts() {
    // Validate nonce and sanitize input in real projects.
    $page = isset($_POST['page']) ? absint($_POST['page']) : 1;

    $query = new WP_Query(array(
        'post_type' => 'post',
        'paged' => $page,
    ));

    // Return HTML or JSON.
    wp_send_json_success(array('message' => 'Posts loaded.'));
}
*/

// JavaScript AJAX idea.
/*
const formData = new FormData();
formData.append('action', 'load_more_posts');
formData.append('page', '2');

fetch('/wp-admin/admin-ajax.php', {
  method: 'POST',
  body: formData
})
  .then(response => response.json())
  .then(data => console.log(data));
*/


/* ========================================================================== */
/* 16. PRACTICAL WORDPRESS PROJECT EXAMPLES                                    */
/* ========================================================================== */

/**
 * 16.1 Agency Website Example
 *
 * Theme:
 * - Custom classic theme or lightweight third-party theme.
 *
 * Plugins:
 * - ACF for structured fields.
 * - Gravity Forms for contact forms.
 * - Yoast/Rank Math for SEO.
 * - WP Rocket or host cache for performance.
 *
 * Custom Post Types:
 * - Case Studies
 * - Team Members
 * - Testimonials
 *
 * Taxonomies:
 * - Industry
 * - Service
 * - Platform
 *
 * Hooks:
 * - Add tracking scripts.
 * - Modify form confirmations.
 * - Add CTA after blog posts.
 */

/**
 * 16.2 Cake Shop / WooCommerce Example
 *
 * Theme:
 * - Elementor-compatible theme or WooCommerce-friendly theme.
 *
 * Plugins:
 * - WooCommerce
 * - Payment gateway plugin
 * - SEO plugin
 * - Contact form plugin
 *
 * Products:
 * - Cookies
 * - Cakes
 * - Gift boxes
 *
 * Custom taxonomies/categories:
 * - Chocolate
 * - Vanilla
 * - Birthday
 * - Gift box
 *
 * Real-life workflow:
 * 1. Customer visits product page.
 * 2. Adds cookies to cart.
 * 3. Chooses local pickup or delivery.
 * 4. Pays online.
 * 5. Store owner receives order in WooCommerce.
 */

/**
 * 16.3 Real Estate Website Example
 *
 * Custom Post Type:
 * - Properties
 *
 * Custom Fields:
 * - Price
 * - Bedrooms
 * - Bathrooms
 * - Area
 * - Address
 *
 * Taxonomies:
 * - Property Type
 * - Location
 * - Status: For Sale, For Rent, Sold
 */


/* ========================================================================== */
/* 17. SIMPLE ANALOGY                                                          */
/* ========================================================================== */

/**
 * Think of WordPress like a library:
 *
 * WordPress         = The library system
 * Database          = The storage room
 * Theme             = The building design/interior decoration
 * Plugin            = Extra services inside the library
 * Widget            = Small information boards
 * Page editor       = Visual layout tool
 * Hook              = A place where developers can attach custom behavior
 * Action            = "Do something here"
 * Filter            = "Modify this before showing it"
 * The Loop          = Display books/posts one by one
 * Shortcode         = A shortcut command
 * Custom Post Type  = A new type of item, like Books, Movies, Courses
 * Taxonomy          = Shelves/categories used to organize items
 */

/* End of WordPress Breakdown with Examples */
