<?php
/**
 * WordPress Breakdown with Examples and Real-Life Use Cases
 * --------------------------------------------------------
 * Purpose:
 * This file is a learning/reference document. It is NOT intended to be installed
 * as a real WordPress plugin or theme file.
 *
 * It combines comments, PHP snippets, pseudo-code, SQL examples, HTML, CSS,
 * JavaScript, and WP-CLI examples to explain common WordPress concepts in a
 * practical way.
 *
 * How to use this file:
 * - Read it as study notes.
 * - Copy individual snippets into a theme/plugin only after adapting them.
 * - Do not upload this entire file to production as-is.
 */

/* ========================================================================== */
/* 1. WORDPRESS BASICS                                                        */
/* ========================================================================== */

/**
 * 1.1 What is WordPress?
 *
 * WordPress is a CMS (Content Management System). It allows users and teams to
 * create, edit, organize, and publish website content without manually editing
 * HTML files every time.
 *
 * Real-life use case:
 * A cake shop wants a website with:
 * - Home page
 * - Menu/products
 * - Contact page
 * - Blog/news
 * - Online orders using WooCommerce
 *
 * Instead of building a full custom admin dashboard from scratch, WordPress gives
 * the client an admin panel where they can edit pages, products, images, and orders.
 */

/**
 * 1.2 PHP in WordPress
 *
 * WordPress is written mainly in PHP. PHP runs on the server and generates the
 * HTML that the browser receives.
 *
 * Real-life use case:
 * When a visitor opens a blog post, WordPress uses PHP to:
 * 1. Receive the request.
 * 2. Ask the database for the post data.
 * 3. Load the active theme template.
 * 4. Print the final HTML.
 */

// Example: basic WordPress template tags usually used inside The Loop.
// These functions would print the current post title and content.
/*
the_title();
the_content();
*/

/**
 * Example HTML generated by PHP after WordPress renders a page:
 *
 * <article>
 *   <h1>How to Choose the Right Cake</h1>
 *   <div class="entry-content">
 *     <p>This is the post content stored in the database.</p>
 *   </div>
 * </article>
 */

/**
 * 1.3 SQL / Database
 *
 * WordPress normally uses MySQL or MariaDB.
 * The database stores most site data:
 * - Pages
 * - Posts
 * - Users
 * - Menus
 * - Plugin settings
 * - Theme settings
 * - WooCommerce orders
 * - Contact form entries, depending on the plugin
 *
 * Real-life use case:
 * A client edits the About page from wp-admin. The page content is not usually
 * saved in a PHP file. It is stored in the database, mainly in wp_posts.
 */

// Example SQL query for learning purposes only.
// This gets the latest 5 published blog posts.
/*
SELECT ID, post_title, post_date
FROM wp_posts
WHERE post_type = 'post'
  AND post_status = 'publish'
ORDER BY post_date DESC
LIMIT 5;
*/

// Example: getting a WordPress option from PHP.
/*
$site_name = get_option('blogname');
echo esc_html($site_name);
*/


/* ========================================================================== */
/* 2. WORDPRESS MAIN CONCEPTS                                                 */
/* ========================================================================== */

/**
 * 2.1 Themes
 *
 * A theme controls the visual appearance and layout of the website.
 * It usually includes PHP templates, CSS files, JavaScript files, images, and
 * theme configuration.
 *
 * Real-life use case:
 * A law firm wants a professional website with:
 * - Header
 * - Navigation menu
 * - Hero section
 * - Practice areas
 * - Attorney profiles
 * - Contact form
 * - Footer
 *
 * A theme provides the base design and structure.
 *
 * Common theme files:
 * - style.css
 * - functions.php
 * - header.php
 * - footer.php
 * - index.php
 * - single.php
 * - page.php
 * - archive.php
 */

/**
 * 2.2 Plugins
 *
 * A plugin adds or modifies functionality without editing WordPress core.
 *
 * Real-life use cases:
 * - Add a contact form: Gravity Forms, WPForms, Contact Form 7.
 * - Add SEO tools: Yoast SEO, Rank Math.
 * - Add e-commerce: WooCommerce.
 * - Add security: Wordfence.
 * - Add custom fields: Advanced Custom Fields (ACF).
 * - Add caching/performance: WP Rocket, LiteSpeed Cache.
 */

// Example: this is the kind of plugin header used by WordPress.
// Do not activate this full file as a plugin. This is only an example.
/*
Plugin Name: Custom Site Helpers
Description: Adds small custom functionality for a specific client website.
Version: 1.0.0
Author: Your Name
*/

/**
 * 2.3 Widgets
 *
 * Widgets are small reusable blocks of content usually placed in sidebars,
 * footers, or widget-ready areas.
 *
 * Real-life use case:
 * A blog sidebar may include:
 * - Search bar
 * - Recent posts
 * - Categories
 * - Newsletter signup
 * - Social media links
 */

/**
 * Example widget-like area in a classic theme template:
 *
 * if ( is_active_sidebar('blog-sidebar') ) {
 *     dynamic_sidebar('blog-sidebar');
 * }
 */


/* ========================================================================== */
/* 3. INSTALLING WORDPRESS                                                    */
/* ========================================================================== */

/**
 * 3.1 Download WordPress
 *
 * Real-life use case:
 * You need to manually install WordPress on a cPanel/Hostinger/GoDaddy server.
 * You download WordPress, upload the files, create a database, and run the setup.
 */

/**
 * 3.2 Create a Database
 *
 * Example database information:
 * - Database name: client_site_db
 * - Database user: client_site_user
 * - Password: strong_password_here
 * - Host: localhost
 *
 * Real-life use case:
 * During the WordPress installer, you enter these credentials so WordPress can
 * save and retrieve site content.
 */

// Example wp-config.php values. Do not use these exact credentials.
/*
define('DB_NAME', 'client_site_db');
define('DB_USER', 'client_site_user');
define('DB_PASSWORD', 'strong_password_here');
define('DB_HOST', 'localhost');
*/

/**
 * 3.3 Upload WordPress Files
 *
 * Common server folders:
 * - public_html/
 * - public_html/clientdomain.com/
 * - htdocs/
 *
 * Real-life use case:
 * You upload WordPress files through File Manager, FTP, SFTP, or SSH.
 */

// Example command-line upload concept, not a full real command.
/*
scp -r wordpress/* user@server:/home/user/public_html/
*/

/**
 * 3.4 Run Installation Script
 *
 * Real-life use case:
 * After files and database are ready, you visit the domain in a browser and
 * WordPress asks for site title, admin username, password, and email.
 */

/**
 * 3.5 LocalWP
 *
 * LocalWP is a friendly local WordPress development app.
 *
 * Real-life use case:
 * Before updating Elementor or WooCommerce on production, you clone the site
 * locally and test the update in a safe environment.
 */

/**
 * 3.6 XAMPP
 *
 * XAMPP provides Apache, PHP, and MariaDB/MySQL locally.
 *
 * Real-life use case:
 * A beginner developer wants to practice WordPress locally at:
 * http://localhost/my-wordpress-site
 */

/**
 * 3.7 VVV
 *
 * VVV is a developer-focused local WordPress environment using Vagrant.
 *
 * Real-life use case:
 * Useful for WordPress core development, plugin testing, and consistent team
 * environments.
 */

/**
 * 3.8 Docker for WordPress
 *
 * Docker runs services in containers.
 *
 * Real-life use case:
 * A team wants the same PHP, MySQL, and WordPress versions for every developer.
 */

// Example docker-compose.yml structure, included as a comment.
/*
version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
*/


/* ========================================================================== */
/* 4. THEMES, THEME TYPES, AND SITE STRUCTURE                                  */
/* ========================================================================== */

/**
 * 4.1 Classic Themes
 *
 * Classic themes rely heavily on PHP templates.
 *
 * Real-life use case:
 * A client has an older WordPress site. To edit the blog post layout, you may
 * need to edit single.php in a child theme.
 */

// Example: simple single.php structure.
/*
get_header();

if ( have_posts() ) :
    while ( have_posts() ) :
        the_post();
        ?>
        <main class="single-post">
            <h1><?php the_title(); ?></h1>
            <div><?php the_content(); ?></div>
        </main>
        <?php
    endwhile;
endif;

get_footer();
*/

/**
 * 4.2 Block Themes
 *
 * Block themes use blocks and the Site Editor to control templates, header,
 * footer, and layouts.
 *
 * Real-life use case:
 * A small business owner wants to edit the header and footer visually from
 * Appearance > Editor without touching PHP files.
 */

/**
 * 4.3 Child Themes
 *
 * A child theme inherits from a parent theme and lets you customize safely.
 *
 * Real-life use case:
 * A client uses Astra. You need custom WooCommerce CSS. You add it to an Astra
 * child theme so the parent theme can still be updated.
 */

// Example child theme style.css header.
/*
Theme Name: Astra Child
Template: astra
Version: 1.0.0
*/

// Example child theme functions.php enqueueing parent/child styles.
/*
add_action('wp_enqueue_scripts', 'astra_child_enqueue_styles');
function astra_child_enqueue_styles() {
    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
    wp_enqueue_style('child-style', get_stylesheet_uri(), array('parent-style'), '1.0.0');
}
*/

/**
 * 4.4 Hybrid Themes
 *
 * Hybrid themes combine PHP templates with block editor features.
 *
 * Real-life use case:
 * The site structure is still controlled by PHP, but page content is managed
 * with Gutenberg blocks.
 */

/**
 * 4.5 Third-Party Themes
 *
 * Third-party themes are made by external companies or developers.
 *
 * Real-life use case:
 * A client has a limited budget and needs a fast launch. You use Kadence,
 * GeneratePress, Astra, Divi, Avada, or a ThemeForest theme as a base.
 *
 * Practical warning:
 * Some multipurpose themes include many features, which can impact performance.
 * Always review scripts, CSS, plugins, and page builder dependencies.
 */

/**
 * 4.6 WordPress File Structure
 *
 * Important folders:
 * - wp-admin/       WordPress admin files.
 * - wp-includes/    WordPress core files.
 * - wp-content/     Themes, plugins, uploads, and custom content.
 *
 * Most developer work happens in:
 * - wp-content/themes/
 * - wp-content/plugins/
 * - wp-content/uploads/
 *
 * Real-life use cases:
 * - Plugin fatal error: rename the plugin folder to disable it.
 * - Missing images: check wp-content/uploads/.
 * - Theme customization: check active theme or child theme folder.
 */

// Example emergency plugin disable via folder rename.
/*
wp-content/plugins/problem-plugin/
wp-content/plugins/problem-plugin-disabled/
*/

/**
 * 4.7 Page Editors
 *
 * Page editors allow visual page building.
 *
 * Common editors/builders:
 * - Gutenberg
 * - Elementor
 * - Beaver Builder
 * - Divi
 * - WPBakery
 *
 * Real-life use case:
 * A marketing team wants to edit landing page content without asking a developer
 * every time. Elementor or Gutenberg can allow controlled visual editing.
 */


/* ========================================================================== */
/* 5. HOOKS: ACTIONS AND FILTERS                                               */
/* ========================================================================== */

/**
 * 5.1 Hooks
 *
 * Hooks allow developers to modify WordPress behavior without editing WordPress
 * core files.
 *
 * Two main types:
 * - Actions: do something at a specific moment.
 * - Filters: modify data before it is displayed or saved.
 */

/**
 * 5.2 Actions
 *
 * Real-life use case:
 * Add a custom script to the footer, register a custom post type, add admin
 * menu pages, or run setup logic.
 */

// Example action: add custom code to the footer.
/*
add_action('wp_footer', 'my_custom_footer_marker');
function my_custom_footer_marker() {
    echo '<!-- Custom footer marker for QA or tracking -->';
}
*/

// Example action: enqueue scripts and styles properly.
/*
add_action('wp_enqueue_scripts', 'my_theme_assets');
function my_theme_assets() {
    wp_enqueue_style(
        'my-theme-style',
        get_stylesheet_uri(),
        array(),
        '1.0.0'
    );

    wp_enqueue_script(
        'my-theme-main-js',
        get_template_directory_uri() . '/assets/js/main.js',
        array('jquery'),
        '1.0.0',
        true
    );
}
*/

// Example action: register a custom post type on init.
/*
add_action('init', 'register_case_study_post_type');
function register_case_study_post_type() {
    register_post_type('case_study', array(
        'label' => 'Case Studies',
        'public' => true,
        'has_archive' => true,
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite' => array('slug' => 'case-studies'),
    ));
}
*/

/**
 * 5.3 Filters
 *
 * Filters modify data and return it.
 *
 * Real-life use case:
 * Add a CTA after blog posts, modify titles, change excerpt length, modify
 * WooCommerce button text, or adjust form output.
 */

// Example filter: add CTA after each single blog post.
/*
add_filter('the_content', 'add_cta_after_blog_post');
function add_cta_after_blog_post($content) {
    if ( is_single() && get_post_type() === 'post' ) {
        $content .= '<div class="post-cta">Need help with your website? Contact us today.</div>';
    }

    return $content;
}
*/

// Example filter: change excerpt length.
/*
add_filter('excerpt_length', 'custom_excerpt_length');
function custom_excerpt_length($length) {
    return 25;
}
*/

/**
 * 5.4 Custom Hooks
 *
 * Developers can create their own hooks inside themes or plugins.
 *
 * Real-life use case:
 * You build a custom plugin and want to let future developers inject extra logic
 * after a custom form is submitted.
 */

// Plugin/theme code creates the action.
/*
do_action('my_plugin_after_form_submit', $submission_id);
*/

// Another developer can hook into it.
/*
add_action('my_plugin_after_form_submit', 'send_internal_notification');
function send_internal_notification($submission_id) {
    // Send email or log the submission.
}
*/


/* ========================================================================== */
/* 6. THE LOOP                                                                 */
/* ========================================================================== */

/**
 * 6.1 The Loop
 *
 * The Loop is how WordPress displays posts/pages from the database.
 *
 * Real-life use case:
 * A blog archive page displays multiple posts. For each post, WordPress prints:
 * - Title
 * - Date
 * - Featured image
 * - Excerpt
 * - Read more link
 */

// Basic Loop example.
/*
if ( have_posts() ) :
    while ( have_posts() ) :
        the_post();
        ?>
        <article id="post-<?php the_ID(); ?>">
            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div class="excerpt"><?php the_excerpt(); ?></div>
        </article>
        <?php
    endwhile;
else :
    echo '<p>No posts found.</p>';
endif;
*/

// Custom WP_Query example: show 6 case studies.
/*
$case_studies = new WP_Query(array(
    'post_type' => 'case_study',
    'posts_per_page' => 6,
));

if ( $case_studies->have_posts() ) :
    while ( $case_studies->have_posts() ) :
        $case_studies->the_post();
        ?>
        <article class="case-study-card">
            <?php the_post_thumbnail('medium'); ?>
            <h3><?php the_title(); ?></h3>
            <?php the_excerpt(); ?>
        </article>
        <?php
    endwhile;
    wp_reset_postdata();
endif;
*/


/* ========================================================================== */
/* 7. SHORTCODES                                                               */
/* ========================================================================== */

/**
 * 7.1 Shortcodes
 *
 * Shortcodes let users insert dynamic content into posts/pages using a simple
 * bracket syntax.
 *
 * Real-life use cases:
 * - Insert a contact form: [gravityform id="3"]
 * - Insert a gallery: [gallery]
 * - Insert current year in footer: [current_year]
 */

// Example custom shortcode: current year.
/*
add_shortcode('current_year', 'show_current_year_shortcode');
function show_current_year_shortcode() {
    return date('Y');
}
*/

/**
 * User can write this in the editor:
 * © [current_year] My Company. All rights reserved.
 *
 * Output:
 * © 2026 My Company. All rights reserved.
 */

// Example shortcode with attributes.
/*
add_shortcode('button', 'custom_button_shortcode');
function custom_button_shortcode($atts) {
    $atts = shortcode_atts(array(
        'url' => '#',
        'label' => 'Click here',
    ), $atts);

    return '<a class="btn" href="' . esc_url($atts['url']) . '">' . esc_html($atts['label']) . '</a>';
}
*/

/**
 * User can write:
 * [button url="/contact" label="Contact us"]
 */


/* ========================================================================== */
/* 8. STYLE AND SCRIPT ENQUEUEING                                              */
/* ========================================================================== */

/**
 * 8.1 Enqueueing
 *
 * Enqueueing is the correct WordPress way to load CSS and JavaScript.
 *
 * Bad approach:
 * Hardcoding scripts directly in header.php or footer.php.
 *
 * Better approach:
 * Use wp_enqueue_style() and wp_enqueue_script().
 *
 * Real-life use case:
 * You need to add custom JavaScript for a mobile menu and custom CSS for a
 * landing page. Enqueueing prevents duplicate loading and helps manage dependencies.
 */

// Example enqueue function.
/*
add_action('wp_enqueue_scripts', 'site_enqueue_assets');
function site_enqueue_assets() {
    wp_enqueue_style(
        'site-main-css',
        get_template_directory_uri() . '/assets/css/main.css',
        array(),
        '1.0.0'
    );

    wp_enqueue_script(
        'site-main-js',
        get_template_directory_uri() . '/assets/js/main.js',
        array(),
        '1.0.0',
        true
    );
}
*/

// Example conditional enqueue: only load CSS on contact page.
/*
add_action('wp_enqueue_scripts', 'contact_page_assets');
function contact_page_assets() {
    if ( is_page('contact') ) {
        wp_enqueue_style(
            'contact-page-css',
            get_template_directory_uri() . '/assets/css/contact.css',
            array(),
            '1.0.0'
        );
    }
}
*/

// Example JavaScript file content for /assets/js/main.js.
/*
document.addEventListener('DOMContentLoaded', function () {
  const menuButton = document.querySelector('.menu-toggle');
  const menu = document.querySelector('.main-menu');

  if (menuButton && menu) {
    menuButton.addEventListener('click', function () {
      menu.classList.toggle('is-open');
    });
  }
});
*/

// Example CSS file content for /assets/css/main.css.
/*
.main-menu {
  display: none;
}

.main-menu.is-open {
  display: block;
}

.btn {
  display: inline-block;
  padding: 12px 20px;
  text-decoration: none;
}
*/


/* ========================================================================== */
/* 9. CUSTOM POST TYPES                                                        */
/* ========================================================================== */

/**
 * 9.1 Custom Post Types
 *
 * Custom Post Types (CPTs) create structured content beyond posts and pages.
 *
 * Real-life examples:
 * - Agency website: Case Studies
 * - Real estate website: Properties
 * - Restaurant website: Menu Items
 * - Doctor website: Doctors
 * - School website: Courses
 * - Portfolio website: Projects
 * - Reviews section: Testimonials
 */

// Example: register Case Studies CPT.
/*
add_action('init', 'register_case_studies_cpt');
function register_case_studies_cpt() {
    register_post_type('case_study', array(
        'labels' => array(
            'name' => 'Case Studies',
            'singular_name' => 'Case Study',
            'add_new_item' => 'Add New Case Study',
            'edit_item' => 'Edit Case Study',
        ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-portfolio',
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite' => array('slug' => 'case-studies'),
        'show_in_rest' => true,
    ));
}
*/

/**
 * Example final URLs:
 * /case-studies/
 * /case-studies/client-name/
 */

/**
 * Real-life structure for an agency Case Study:
 * - Title: "How We Increased Leads by 130%"
 * - Featured image: Client logo or campaign image
 * - Content: Problem, solution, results
 * - Custom fields: Industry, services, result percentage, client testimonial
 */


/* ========================================================================== */
/* 10. TAXONOMIES                                                              */
/* ========================================================================== */

/**
 * 10.1 Taxonomies
 *
 * Taxonomies organize content into groups.
 *
 * Default taxonomies:
 * - Categories
 * - Tags
 *
 * Custom taxonomy examples:
 * - Properties: Location, Property Type, Price Range
 * - Case Studies: Industry, Service, Platform
 * - Courses: Level, Topic, Instructor
 */

// Example: register Industry taxonomy for Case Studies.
/*
add_action('init', 'register_case_study_industry_taxonomy');
function register_case_study_industry_taxonomy() {
    register_taxonomy('industry', array('case_study'), array(
        'labels' => array(
            'name' => 'Industries',
            'singular_name' => 'Industry',
        ),
        'public' => true,
        'hierarchical' => true,
        'rewrite' => array('slug' => 'case-studies/industry'),
        'show_in_rest' => true,
    ));
}
*/

/**
 * Example final taxonomy URLs:
 * /case-studies/industry/healthcare/
 * /case-studies/industry/ecommerce/
 */


/* ========================================================================== */
/* 11. CUSTOM FIELDS AND ACF                                                   */
/* ========================================================================== */

/**
 * 11.1 Custom Fields
 *
 * Custom fields store extra structured data for posts, pages, CPTs, and users.
 *
 * Real-life use case:
 * A Case Study needs fields that are not part of normal post content:
 * - Client name
 * - Industry
 * - Revenue increase
 * - Lead increase
 * - Testimonial
 *
 * ACF (Advanced Custom Fields) makes this easier through the admin UI.
 */

// Example ACF field usage in a template.
/*
$client_name = get_field('client_name');
$lead_increase = get_field('lead_increase');

if ( $client_name ) {
    echo '<p>Client: ' . esc_html($client_name) . '</p>';
}

if ( $lead_increase ) {
    echo '<p>Lead increase: ' . esc_html($lead_increase) . '%</p>';
}
*/

// Native WordPress custom field usage.
/*
$subtitle = get_post_meta(get_the_ID(), 'subtitle', true);
if ( $subtitle ) {
    echo '<p class="subtitle">' . esc_html($subtitle) . '</p>';
}
*/


/* ========================================================================== */
/* 12. WOOCOMMERCE EXAMPLES                                                    */
/* ========================================================================== */

/**
 * 12.1 WooCommerce
 *
 * WooCommerce adds e-commerce functionality to WordPress.
 *
 * Real-life use case:
 * A local cake shop wants to sell cookies online for local delivery/pickup.
 * WooCommerce can manage:
 * - Products
 * - Cart
 * - Checkout
 * - Orders
 * - Payment gateways
 * - Shipping/local pickup
 */

// Example: change Add to Cart button text.
/*
add_filter('woocommerce_product_single_add_to_cart_text', 'custom_add_to_cart_text');
function custom_add_to_cart_text() {
    return 'Order Now';
}
*/

// Example: show a message above checkout.
/*
add_action('woocommerce_before_checkout_form', 'local_delivery_checkout_notice');
function local_delivery_checkout_notice() {
    echo '<p class="checkout-notice">Local delivery is available only inside selected city areas.</p>';
}
*/


/* ========================================================================== */
/* 13. WORDPRESS SECURITY AND MAINTENANCE                                      */
/* ========================================================================== */

/**
 * 13.1 Updates and Backups
 *
 * Real-life use case:
 * Before updating Elementor, WooCommerce, or a theme, you should:
 * 1. Confirm there is a recent backup.
 * 2. Test on staging if possible.
 * 3. Apply updates.
 * 4. Test key pages and forms.
 * 5. Clear cache.
 */

/**
 * 13.2 Security Plugins
 *
 * Real-life use case:
 * A site receives an unauthorized admin user alert. You may:
 * - Remove unknown users.
 * - Change admin passwords.
 * - Install/check Wordfence or another security plugin.
 * - Review recently modified files.
 * - Check hosting logs.
 * - Update outdated plugins/themes.
 */

// Example: disable file editing from wp-admin in wp-config.php.
/*
define('DISALLOW_FILE_EDIT', true);
*/

// Example: force SSL admin in wp-config.php.
/*
define('FORCE_SSL_ADMIN', true);
*/


/* ========================================================================== */
/* 14. PERFORMANCE AND CACHE                                                   */
/* ========================================================================== */

/**
 * 14.1 Caching
 *
 * Caching stores generated pages/assets so the server does not need to rebuild
 * everything on every request.
 *
 * Real-life use case:
 * A marketing site loads slowly because every request triggers many PHP/database
 * operations. A cache plugin or host-level cache can serve faster HTML.
 *
 * Common cache layers:
 * - Browser cache
 * - Plugin cache
 * - Host/server cache
 * - CDN cache
 * - Object cache
 */

/**
 * 14.2 Performance Practical Checks
 *
 * Real-life use cases:
 * - Clear cache after CSS changes do not appear.
 * - Regenerate Elementor CSS if frontend styles are broken.
 * - Check if JavaScript optimization delays important clicks.
 * - Review image sizes if pages are heavy.
 */

// Example WP-CLI commands for maintenance.
/*
wp cache flush
wp transient delete --all
wp plugin list
wp theme list
wp option get blogname
*/


/* ========================================================================== */
/* 15. REST API AND AJAX                                                       */
/* ========================================================================== */

/**
 * 15.1 REST API
 *
 * WordPress includes a REST API that can expose content as JSON.
 *
 * Real-life use case:
 * A JavaScript frontend needs to fetch the latest blog posts from WordPress.
 * It can request:
 * /wp-json/wp/v2/posts
 */

// Example JavaScript fetch request.
/*
fetch('/wp-json/wp/v2/posts?per_page=3')
  .then(response => response.json())
  .then(posts => {
    posts.forEach(post => {
      console.log(post.title.rendered);
    });
  });
*/

// Example custom REST endpoint.
/*
add_action('rest_api_init', function () {
    register_rest_route('site/v1', '/status', array(
        'methods' => 'GET',
        'callback' => function () {
            return array(
                'status' => 'ok',
                'site' => get_bloginfo('name'),
            );
        },
        'permission_callback' => '__return_true',
    ));
});
*/

/**
 * 15.2 AJAX
 *
 * AJAX allows frontend interactions without a full page reload.
 *
 * Real-life use case:
 * A "Load More" button loads more case studies without refreshing the page.
 */

// PHP AJAX handler example.
/*
add_action('wp_ajax_load_more_posts', 'load_more_posts');
add_action('wp_ajax_nopriv_load_more_posts', 'load_more_posts');

function load_more_posts() {
    // Validate nonce and sanitize input in real projects.
    $page = isset($_POST['page']) ? absint($_POST['page']) : 1;

    $query = new WP_Query(array(
        'post_type' => 'post',
        'paged' => $page,
    ));

    // Return HTML or JSON.
    wp_send_json_success(array('message' => 'Posts loaded.'));
}
*/

// JavaScript AJAX idea.
/*
const formData = new FormData();
formData.append('action', 'load_more_posts');
formData.append('page', '2');

fetch('/wp-admin/admin-ajax.php', {
  method: 'POST',
  body: formData
})
  .then(response => response.json())
  .then(data => console.log(data));
*/


/* ========================================================================== */
/* 16. PRACTICAL WORDPRESS PROJECT EXAMPLES                                    */
/* ========================================================================== */

/**
 * 16.1 Agency Website Example
 *
 * Theme:
 * - Custom classic theme or lightweight third-party theme.
 *
 * Plugins:
 * - ACF for structured fields.
 * - Gravity Forms for contact forms.
 * - Yoast/Rank Math for SEO.
 * - WP Rocket or host cache for performance.
 *
 * Custom Post Types:
 * - Case Studies
 * - Team Members
 * - Testimonials
 *
 * Taxonomies:
 * - Industry
 * - Service
 * - Platform
 *
 * Hooks:
 * - Add tracking scripts.
 * - Modify form confirmations.
 * - Add CTA after blog posts.
 */

/**
 * 16.2 Cake Shop / WooCommerce Example
 *
 * Theme:
 * - Elementor-compatible theme or WooCommerce-friendly theme.
 *
 * Plugins:
 * - WooCommerce
 * - Payment gateway plugin
 * - SEO plugin
 * - Contact form plugin
 *
 * Products:
 * - Cookies
 * - Cakes
 * - Gift boxes
 *
 * Custom taxonomies/categories:
 * - Chocolate
 * - Vanilla
 * - Birthday
 * - Gift box
 *
 * Real-life workflow:
 * 1. Customer visits product page.
 * 2. Adds cookies to cart.
 * 3. Chooses local pickup or delivery.
 * 4. Pays online.
 * 5. Store owner receives order in WooCommerce.
 */

/**
 * 16.3 Real Estate Website Example
 *
 * Custom Post Type:
 * - Properties
 *
 * Custom Fields:
 * - Price
 * - Bedrooms
 * - Bathrooms
 * - Area
 * - Address
 *
 * Taxonomies:
 * - Property Type
 * - Location
 * - Status: For Sale, For Rent, Sold
 */


/* ========================================================================== */
/* 17. SIMPLE ANALOGY                                                          */
/* ========================================================================== */

/**
 * Think of WordPress like a library:
 *
 * WordPress         = The library system
 * Database          = The storage room
 * Theme             = The building design/interior decoration
 * Plugin            = Extra services inside the library
 * Widget            = Small information boards
 * Page editor       = Visual layout tool
 * Hook              = A place where developers can attach custom behavior
 * Action            = "Do something here"
 * Filter            = "Modify this before showing it"
 * The Loop          = Display books/posts one by one
 * Shortcode         = A shortcut command
 * Custom Post Type  = A new type of item, like Books, Movies, Courses
 * Taxonomy          = Shelves/categories used to organize items
 */

/* End of WordPress Breakdown with Examples */

/* ========================================================================== */
/* 18. WORDPRESS REST API                                                     */
/* ========================================================================== */

/**
 * The WordPress REST API is an interface that allows other applications,
 * websites, mobile apps, JavaScript frontends, and external services to
 * communicate with a WordPress site.
 *
 * In simple terms:
 *
 * The REST API lets WordPress send and receive data using URLs.
 *
 * Instead of only using the WordPress admin dashboard to manage content,
 * developers can use HTTP requests to read, create, update, or delete data.
 *
 * The REST API uses common HTTP methods:
 *
 * GET    = Read data
 * POST   = Create new data
 * PUT    = Replace/update existing data
 * PATCH  = Partially update existing data
 * DELETE = Delete data
 *
 * WordPress exposes REST API endpoints under this base URL:
 *
 * https://example.com/wp-json/
 *
 * A common endpoint for posts is:
 *
 * https://example.com/wp-json/wp/v2/posts
 *
 * A common endpoint for pages is:
 *
 * https://example.com/wp-json/wp/v2/pages
 *
 * A common endpoint for users is:
 *
 * https://example.com/wp-json/wp/v2/users
 *
 * A common endpoint for media files is:
 *
 * https://example.com/wp-json/wp/v2/media
 */


/* -------------------------------------------------------------------------- */
/* 18.1 BASIC REAL-LIFE USE CASE                                              */
/* -------------------------------------------------------------------------- */

/**
 * Real-life example:
 *
 * Imagine a WordPress website that has blog posts, but you want to display
 * those blog posts inside a separate React, Vue, Next.js, or mobile app.
 *
 * Instead of manually copying the posts, the external app can request them
 * from WordPress using the REST API.
 *
 * Example request:
 *
 * GET https://example.com/wp-json/wp/v2/posts
 *
 * WordPress responds with JSON data.
 *
 * JSON means JavaScript Object Notation. It is a common format used to
 * exchange data between systems.
 *
 * Example simplified JSON response:
 *
 * [
 *   {
 *     "id": 10,
 *     "date": "2026-06-24T10:00:00",
 *     "slug": "my-first-post",
 *     "title": {
 *       "rendered": "My First Post"
 *     },
 *     "content": {
 *       "rendered": "<p>This is the post content.</p>"
 *     }
 *   }
 * ]
 *
 * A frontend app can then take this data and display it however it wants.
 */


/* -------------------------------------------------------------------------- */
/* 18.2 COMMON WORDPRESS REST API ENDPOINTS                                   */
/* -------------------------------------------------------------------------- */

/**
 * Some common default WordPress REST API endpoints:
 *
 * Posts:
 * https://example.com/wp-json/wp/v2/posts
 *
 * Single post by ID:
 * https://example.com/wp-json/wp/v2/posts/10
 *
 * Pages:
 * https://example.com/wp-json/wp/v2/pages
 *
 * Single page by ID:
 * https://example.com/wp-json/wp/v2/pages/25
 *
 * Categories:
 * https://example.com/wp-json/wp/v2/categories
 *
 * Tags:
 * https://example.com/wp-json/wp/v2/tags
 *
 * Media:
 * https://example.com/wp-json/wp/v2/media
 *
 * Users:
 * https://example.com/wp-json/wp/v2/users
 *
 * Comments:
 * https://example.com/wp-json/wp/v2/comments
 *
 * Search:
 * https://example.com/wp-json/wp/v2/search?search=wordpress
 */


/* -------------------------------------------------------------------------- */
/* 18.3 EXAMPLE: FETCH POSTS WITH JAVASCRIPT                                  */
/* -------------------------------------------------------------------------- */

/**
 * Real-life use case:
 *
 * You are building a custom frontend with JavaScript and you want to display
 * the latest blog posts from WordPress.
 *
 * This could be used in:
 *
 * - A React app
 * - A Vue app
 * - A static landing page
 * - A custom dashboard
 * - A mobile app using a web view
 */

/*
?>

<script>
fetch('https://example.com/wp-json/wp/v2/posts')
    .then(response => response.json())
    .then(posts => {
        console.log(posts);

        posts.forEach(post => {
            console.log(post.title.rendered);
            console.log(post.link);
        });
    })
    .catch(error => {
        console.error('Error fetching posts:', error);
    });
</script>

<?php
*/

/* -------------------------------------------------------------------------- */
/* 18.4 EXAMPLE: FETCH POSTS WITH PHP                                         */
/* -------------------------------------------------------------------------- */

/**
 * Real-life use case:
 *
 * You have one WordPress site and you want to show posts from another
 * WordPress site.
 *
 * Example:
 *
 * Site A is the company website.
 * Site B is the company blog.
 *
 * You want to display the latest blog posts from Site B on Site A.
 */

/*
$response = wp_remote_get('https://example.com/wp-json/wp/v2/posts');

if (!is_wp_error($response)) {
    $body = wp_remote_retrieve_body($response);
    $posts = json_decode($body);

    if (!empty($posts)) {
        foreach ($posts as $post) {
            echo '<h2>' . esc_html($post->title->rendered) . '</h2>';
            echo '<a href="' . esc_url($post->link) . '">Read more</a>';
        }
    }
}
*/

/* -------------------------------------------------------------------------- */
/* 18.5 EXAMPLE: LIMIT THE NUMBER OF POSTS                                    */
/* -------------------------------------------------------------------------- */

/**
 * By default, WordPress may return several posts.
 *
 * You can use query parameters to control the response.
 *
 * Example:
 *
 * Get only 3 posts:
 *
 * https://example.com/wp-json/wp/v2/posts?per_page=3
 *
 * Get posts from category ID 5:
 *
 * https://example.com/wp-json/wp/v2/posts?categories=5
 *
 * Search posts containing the word "seo":
 *
 * https://example.com/wp-json/wp/v2/posts?search=seo
 *
 * Order posts by newest first:
 *
 * https://example.com/wp-json/wp/v2/posts?orderby=date&order=desc
 */


/* -------------------------------------------------------------------------- */
/* 18.6 EXAMPLE: HEADLESS WORDPRESS                                           */
/* -------------------------------------------------------------------------- */

/**
 * Headless WordPress means WordPress is used only as the backend/CMS,
 * while the frontend is built with another technology.
 *
 * Traditional WordPress:
 *
 * WordPress Admin + WordPress Theme + WordPress Frontend
 *
 * Headless WordPress:
 *
 * WordPress Admin + REST API + Custom Frontend
 *
 * Example frontend technologies:
 *
 * - React
 * - Next.js
 * - Vue
 * - Nuxt
 * - Angular
 * - Astro
 * - Mobile apps
 *
 * Real-life use case:
 *
 * A marketing team wants to keep using WordPress because they already know
 * how to write and edit content there.
 *
 * But the development team wants a custom frontend built with Next.js for
 * better performance, custom routing, and a modern user experience.
 *
 * In that case:
 *
 * - Editors create posts in WordPress.
 * - Next.js fetches the content through the REST API.
 * - Visitors see the Next.js frontend, not a normal WordPress theme.
 */


/* -------------------------------------------------------------------------- */
/* 18.7 EXAMPLE: CREATE A CUSTOM REST API ENDPOINT                            */
/* -------------------------------------------------------------------------- */

/**
 * WordPress allows developers to create custom REST API endpoints.
 *
 * Real-life use case:
 *
 * You have a custom post type called "case_study" and you want to expose
 * a simplified endpoint that returns only the fields needed by the frontend.
 *
 * Example endpoint:
 *
 * https://example.com/wp-json/rocadev/v1/case-studies
 *
 * This is useful when the default WordPress REST API response contains too
 * much data or when you want to control exactly what is returned.
 */

/*
add_action('rest_api_init', 'rocadev_register_case_studies_endpoint');

function rocadev_register_case_studies_endpoint() {
    register_rest_route('rocadev/v1', '/case-studies', [
        'methods'  => 'GET',
        'callback' => 'rocadev_get_case_studies',
        'permission_callback' => '__return_true',
    ]);
}

function rocadev_get_case_studies() {
    $query = new WP_Query([
        'post_type'      => 'case_study',
        'posts_per_page' => 10,
        'post_status'    => 'publish',
    ]);

    $results = [];

    if ($query->have_posts()) {
        while ($query->have_posts()) {
            $query->the_post();

            $results[] = [
                'id'        => get_the_ID(),
                'title'     => get_the_title(),
                'excerpt'   => get_the_excerpt(),
                'permalink' => get_permalink(),
                'image'     => get_the_post_thumbnail_url(get_the_ID(), 'medium'),
            ];
        }

        wp_reset_postdata();
    }

    return rest_ensure_response($results);
}
*/

/* -------------------------------------------------------------------------- */
/* 18.8 EXAMPLE: CUSTOM ENDPOINT WITH PARAMETERS                              */
/* -------------------------------------------------------------------------- */

/**
 * Real-life use case:
 *
 * You want an endpoint that returns case studies filtered by industry.
 *
 * Example:
 *
 * https://example.com/wp-json/rocadev/v1/case-studies?industry=healthcare
 *
 * This could be useful for:
 *
 * - Filtering case studies
 * - Building frontend search
 * - Creating dynamic landing pages
 * - Connecting WordPress to another application
 */

/*
add_action('rest_api_init', 'rocadev_register_filtered_case_studies_endpoint');

function rocadev_register_filtered_case_studies_endpoint() {
    register_rest_route('rocadev/v1', '/filtered-case-studies', [
        'methods'  => 'GET',
        'callback' => 'rocadev_get_filtered_case_studies',
        'permission_callback' => '__return_true',
        'args' => [
            'industry' => [
                'required' => false,
                'sanitize_callback' => 'sanitize_text_field',
            ],
        ],
    ]);
}

function rocadev_get_filtered_case_studies($request) {
    $industry = $request->get_param('industry');

    $args = [
        'post_type'      => 'case_study',
        'posts_per_page' => 10,
        'post_status'    => 'publish',
    ];

    if (!empty($industry)) {
        $args['tax_query'] = [
            [
                'taxonomy' => 'industry',
                'field'    => 'slug',
                'terms'    => $industry,
            ],
        ];
    }

    $query = new WP_Query($args);

    $results = [];

    if ($query->have_posts()) {
        while ($query->have_posts()) {
            $query->the_post();

            $results[] = [
                'title'     => get_the_title(),
                'permalink' => get_permalink(),
            ];
        }

        wp_reset_postdata();
    }

    return rest_ensure_response($results);
}
*/

/* -------------------------------------------------------------------------- */
/* 18.9 AUTHENTICATION                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Public REST API requests usually do not need authentication.
 *
 * Example:
 *
 * Reading published posts is usually public:
 *
 * GET https://example.com/wp-json/wp/v2/posts
 *
 * But creating, updating, or deleting content usually requires authentication.
 *
 * Example:
 *
 * Creating a post:
 *
 * POST https://example.com/wp-json/wp/v2/posts
 *
 * Updating a post:
 *
 * PUT https://example.com/wp-json/wp/v2/posts/10
 *
 * Deleting a post:
 *
 * DELETE https://example.com/wp-json/wp/v2/posts/10
 *
 * These actions should only be available to authorized users.
 *
 * Common authentication methods:
 *
 * - WordPress cookies and nonces, usually inside WordPress admin.
 * - Application Passwords.
 * - OAuth, usually in more complex integrations.
 * - JWT, commonly used in headless setups with plugins.
 *
 * Real-life use case:
 *
 * A mobile app lets an authenticated editor create blog posts from their phone.
 * The app sends the post title and content to WordPress using the REST API.
 */


/* -------------------------------------------------------------------------- */
/* 18.10 EXAMPLE: CREATE A POST WITH THE REST API                             */
/* -------------------------------------------------------------------------- */

/**
 * This example is only conceptual.
 *
 * To actually create a post, the request must be authenticated.
 *
 * Example request:
 *
 * POST https://example.com/wp-json/wp/v2/posts
 *
 * Body:
 *
 * {
 *   "title": "New Post from External App",
 *   "content": "This post was created using the REST API.",
 *   "status": "publish"
 * }
 *
 * Real-life use case:
 *
 * A custom CRM automatically creates a private WordPress post every time
 * a new customer case is created.
 */


/* -------------------------------------------------------------------------- */
/* 18.11 EXAMPLE: APPLICATION PASSWORDS                                       */
/* -------------------------------------------------------------------------- */

/**
 * Application Passwords allow external applications to authenticate with
 * WordPress without using the user's normal password directly.
 *
 * Real-life use case:
 *
 * You connect a third-party automation tool to WordPress so it can create
 * draft posts automatically.
 *
 * Example with cURL:
 *
 * curl --user "username:application-password" \
 *      -X POST https://example.com/wp-json/wp/v2/posts \
 *      -H "Content-Type: application/json" \
 *      -d '{
 *            "title": "Post created from cURL",
 *            "content": "This content was sent through the REST API.",
 *            "status": "draft"
 *          }'
 *
 * Important:
 *
 * Application passwords should be treated like real passwords.
 * Do not commit them to GitHub.
 * Do not expose them in frontend JavaScript.
 * Revoke them when they are no longer needed.
 */


/* -------------------------------------------------------------------------- */
/* 18.12 NONCES IN WORDPRESS REST API                                         */
/* -------------------------------------------------------------------------- */

/**
 * A nonce is a security token used by WordPress to verify that a request
 * comes from a valid source.
 *
 * In WordPress admin or frontend logged-in experiences, REST API requests
 * often use a nonce.
 *
 * Real-life use case:
 *
 * You build a frontend button that lets a logged-in user save a favorite post.
 *
 * The JavaScript sends a REST API request.
 * WordPress checks the nonce before allowing the action.
 */

/*
wp_localize_script('custom-script', 'rocadevApi', [
    'root'  => esc_url_raw(rest_url()),
    'nonce' => wp_create_nonce('wp_rest'),
]);

?>

<script>
fetch(rocadevApi.root + 'rocadev/v1/favorite-post', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'X-WP-Nonce': rocadevApi.nonce
    },
    body: JSON.stringify({
        post_id: 123
    })
});
</script>

<?php
*/

/* -------------------------------------------------------------------------- */
/* 18.13 PERMISSION CALLBACK                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Every custom REST API route should define a permission_callback.
 *
 * This controls who can access the endpoint.
 *
 * Public endpoint:
 */

// 'permission_callback' => '__return_true';

/**
 * The example above means anyone can access the endpoint.
 *
 * That is acceptable for public data like published posts, public case studies,
 * public testimonials, or public products.
 *
 * Private endpoint example:
 */
/*
'permission_callback' => function () {
    return current_user_can('manage_options');
};
*/

/**
 * The example above means only admins can access the endpoint.
 *
 * Real-life use case:
 *
 * You create an endpoint that returns internal lead data from a contact form.
 * That endpoint should not be public.
 *
 * It should check permissions before returning any data.
 */


/* -------------------------------------------------------------------------- */
/* 18.14 SECURITY CONSIDERATIONS                                              */
/* -------------------------------------------------------------------------- */

/**
 * Important security rules when working with the REST API:
 *
 * 1. Do not expose sensitive data publicly.
 *
 * Bad example:
 *
 * Returning customer emails, phone numbers, order data, private notes,
 * API keys, or user personal information from a public endpoint.
 *
 * 2. Always sanitize input.
 *
 * If an endpoint receives data from a request, clean it before using it.
 */

// $search = sanitize_text_field($request->get_param('search'));

/**
 * 3. Always escape output when rendering data in HTML.
 */

// echo esc_html($title);
// echo esc_url($url);

/**
 * 4. Use permission_callback correctly.
 *
 * Do not use __return_true for private data.
 *
 * 5. Avoid exposing usernames unnecessarily.
 *
 * Some WordPress REST API user endpoints can reveal public user information.
 * Depending on the project, this may be acceptable or may need to be restricted.
 *
 * 6. Never expose secrets in JavaScript.
 *
 * API keys, application passwords, private tokens, and server credentials
 * should never be placed in frontend code.
 */


/* -------------------------------------------------------------------------- */
/* 18.15 REST API AND CUSTOM POST TYPES                                       */
/* -------------------------------------------------------------------------- */

/**
 * Custom Post Types can be exposed in the REST API by setting:
 *
 * 'show_in_rest' => true
 *
 * Real-life use case:
 *
 * You create a "Projects" custom post type and want Gutenberg, the REST API,
 * or a React frontend to access it.
 */

/*

add_action('init', 'rocadev_register_project_post_type');

function rocadev_register_project_post_type() {
    register_post_type('project', [
        'label'        => 'Projects',
        'public'       => true,
        'show_in_rest' => true,
        'supports'     => ['title', 'editor', 'thumbnail', 'excerpt'],
        'rewrite'      => ['slug' => 'projects'],
    ]);
}
*/

/**
 * After this, WordPress creates a REST API endpoint like:
 *
 * https://example.com/wp-json/wp/v2/project
 *
 * In some cases, the endpoint may use the REST base configured for the
 * post type.
 */


/* -------------------------------------------------------------------------- */
/* 18.16 REST API AND ACF                                                     */
/* -------------------------------------------------------------------------- */

/**
 * ACF means Advanced Custom Fields.
 *
 * ACF is commonly used to add custom fields to posts, pages, and custom
 * post types.
 *
 * Real-life use case:
 *
 * A Case Study has fields like:
 *
 * - Client name
 * - Industry
 * - Monthly ad spend
 * - Results
 * - Testimonial
 *
 * These fields can be exposed through the REST API, depending on ACF settings.
 *
 * Example conceptual JSON response:
 *
 * {
 *   "title": {
 *     "rendered": "Dental Clinic Case Study"
 *   },
 *   "acf": {
 *     "client_name": "ABC Dental",
 *     "industry": "Healthcare",
 *     "result": "42% increase in leads"
 *   }
 * }
 *
 * This is useful for a headless frontend that needs structured content.
 */


/* -------------------------------------------------------------------------- */
/* 18.17 EXAMPLE: MODIFY REST API RESPONSE                                    */
/* -------------------------------------------------------------------------- */

/**
 * Developers can add extra fields to REST API responses.
 *
 * Real-life use case:
 *
 * By default, the posts endpoint may not return the featured image URL in
 * the exact format you want.
 *
 * You can register a custom field called featured_image_url.
 */

/*
add_action('rest_api_init', 'rocadev_add_featured_image_to_posts_api');

function rocadev_add_featured_image_to_posts_api() {
    register_rest_field('post', 'featured_image_url', [
        'get_callback' => 'rocadev_get_featured_image_url',
        'schema' => [
            'description' => 'Featured image URL',
            'type'        => 'string',
            'context'     => ['view', 'edit'],
        ],
    ]);
}

function rocadev_get_featured_image_url($object) {
    $post_id = $object['id'];

    $image_url = get_the_post_thumbnail_url($post_id, 'large');

    return $image_url ? $image_url : '';
}
*/

/**
 * After this, each post response can include:
 *
 * {
 *   "id": 10,
 *   "title": {
 *     "rendered": "Example Post"
 *   },
 *   "featured_image_url": "https://example.com/image.jpg"
 * }
 */


/* -------------------------------------------------------------------------- */
/* 18.18 EXAMPLE: DISABLE OR RESTRICT REST API ACCESS                         */
/* -------------------------------------------------------------------------- */

/**
 * In some projects, you may want to restrict certain REST API endpoints.
 *
 * Real-life use case:
 *
 * A security audit recommends limiting public access to user data.
 *
 * Example: restrict user endpoint access to logged-in users only.
 */

/*
add_filter('rest_endpoints', 'rocadev_restrict_users_endpoint');

function rocadev_restrict_users_endpoint($endpoints) {
    if (!is_user_logged_in()) {
        unset($endpoints['/wp/v2/users']);
        unset($endpoints['/wp/v2/users/(?P<id>[\d]+)']);
    }

    return $endpoints;
}
*/

/**
 * Important:
 *
 * Be careful when disabling REST API endpoints.
 * Some plugins, themes, Gutenberg, WooCommerce, and admin features may rely
 * on the REST API.
 */


/* -------------------------------------------------------------------------- */
/* 18.19 REST API WITH WOOCOMMERCE                                            */
/* -------------------------------------------------------------------------- */

/**
 * WooCommerce has its own REST API.
 *
 * Real-life use cases:
 *
 * - Connect WooCommerce to an external inventory system.
 * - Send orders to a shipping provider.
 * - Sync products with a marketplace.
 * - Build a mobile app for customers.
 * - Build a custom admin dashboard for sales reports.
 *
 * Example conceptual endpoint:
 *
 * https://example.com/wp-json/wc/v3/products
 *
 * Example:
 *
 * An external warehouse system checks WooCommerce orders every 10 minutes.
 * When a new paid order appears, the warehouse system prepares the shipment.
 */


/* -------------------------------------------------------------------------- */
/* 18.20 REST API VS AJAX IN WORDPRESS                                        */
/* -------------------------------------------------------------------------- */

/**
 * WordPress historically used admin-ajax.php for many AJAX requests.
 *
 * REST API is now often preferred for structured application-like requests.
 *
 * AJAX example:
 *
 * https://example.com/wp-admin/admin-ajax.php
 *
 * REST API example:
 *
 * https://example.com/wp-json/rocadev/v1/search
 *
 * Real-life comparison:
 *
 * AJAX can be fine for small legacy features.
 *
 * REST API is usually better when:
 *
 * - You are building a structured frontend app.
 * - You need clean URLs.
 * - You want predictable JSON responses.
 * - You are integrating with external systems.
 * - You need custom endpoints.
 */


/* -------------------------------------------------------------------------- */
/* 18.21 PRACTICAL EXAMPLE: CUSTOM SEARCH ENDPOINT                            */
/* -------------------------------------------------------------------------- */

/**
 * Real-life use case:
 *
 * You are building a custom live search component.
 *
 * Instead of loading a full WordPress page, JavaScript sends the search term
 * to a REST API endpoint and receives matching posts as JSON.
 */

/*

add_action('rest_api_init', 'rocadev_register_search_endpoint');

function rocadev_register_search_endpoint() {
    register_rest_route('rocadev/v1', '/search', [
        'methods'  => 'GET',
        'callback' => 'rocadev_rest_search',
        'permission_callback' => '__return_true',
        'args' => [
            'term' => [
                'required' => true,
                'sanitize_callback' => 'sanitize_text_field',
            ],
        ],
    ]);
}

function rocadev_rest_search($request) {
    $term = $request->get_param('term');

    $query = new WP_Query([
        'post_type'      => ['post', 'page'],
        'posts_per_page' => 5,
        's'              => $term,
        'post_status'    => 'publish',
    ]);

    $results = [];

    if ($query->have_posts()) {
        while ($query->have_posts()) {
            $query->the_post();

            $results[] = [
                'title' => get_the_title(),
                'url'   => get_permalink(),
                'type'  => get_post_type(),
            ];
        }

        wp_reset_postdata();
    }

    return rest_ensure_response($results);
}

*/


/* -------------------------------------------------------------------------- */
/* 18.22 FRONTEND JAVASCRIPT FOR CUSTOM SEARCH                                */
/* -------------------------------------------------------------------------- */

/**
 * This is a conceptual JavaScript example for consuming the search endpoint.
 */

/*
?>

<input type="search" id="site-search" placeholder="Search..." />
<div id="search-results"></div>

<script>
const input = document.getElementById('site-search');
const resultsContainer = document.getElementById('search-results');

input.addEventListener('input', function () {
    const term = input.value.trim();

    if (term.length < 3) {
        resultsContainer.innerHTML = '';
        return;
    }

    fetch('/wp-json/rocadev/v1/search?term=' + encodeURIComponent(term))
        .then(response => response.json())
        .then(results => {
            resultsContainer.innerHTML = '';

            results.forEach(item => {
                const link = document.createElement('a');
                link.href = item.url;
                link.textContent = item.title;

                resultsContainer.appendChild(link);
                resultsContainer.appendChild(document.createElement('br'));
            });
        });
});
</script>

<?php

*/

/* -------------------------------------------------------------------------- */
/* 18.23 PERFORMANCE CONSIDERATIONS                                           */
/* -------------------------------------------------------------------------- */

/**
 * REST API endpoints can affect performance if they are not designed well.
 *
 * Common problems:
 *
 * - Returning too much data.
 * - Running heavy database queries.
 * - Not limiting posts_per_page.
 * - Not caching expensive responses.
 * - Calling the API too many times from the frontend.
 *
 * Real-life example:
 *
 * Bad:
 *
 * A homepage calls 15 different REST API endpoints on page load.
 *
 * Better:
 *
 * Create one optimized endpoint that returns only the data needed by the
 * homepage.
 *
 * Example:
 *
 * /wp-json/rocadev/v1/homepage-data
 *
 * This endpoint could return:
 *
 * - Hero content
 * - Latest 3 posts
 * - Featured case studies
 * - Testimonials
 *
 * in one single request.
 */


/* -------------------------------------------------------------------------- */
/* 18.24 DEBUGGING REST API                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Ways to test or debug REST API endpoints:
 *
 * 1. Browser
 *
 * Open a GET endpoint directly:
 *
 * https://example.com/wp-json/wp/v2/posts
 *
 * 2. Postman or Insomnia
 *
 * Useful for testing GET, POST, PUT, PATCH, and DELETE requests.
 *
 * 3. cURL
 *
 * Example:
 *
 * curl https://example.com/wp-json/wp/v2/posts
 *
 * 4. Browser DevTools
 *
 * Open the Network tab and check REST API requests.
 *
 * Useful when debugging Gutenberg, WooCommerce blocks, or custom JavaScript.
 *
 * 5. WordPress debug log
 *
 * Use error_log() inside callbacks during development.
 */

// error_log('REST API endpoint was called');


/* -------------------------------------------------------------------------- */
/* 18.25 SUMMARY                                                              */
/* -------------------------------------------------------------------------- */

/**
 * The WordPress REST API is important because it allows WordPress to work
 * as more than a traditional website builder.
 *
 * It allows WordPress to become a content hub that can communicate with:
 *
 * - JavaScript applications
 * - Mobile apps
 * - CRMs
 * - ERPs
 * - Marketing platforms
 * - Automation tools
 * - External dashboards
 * - E-commerce systems
 *
 * Simple practical examples:
 *
 * 1. Display WordPress posts in a React app.
 * 2. Send WooCommerce orders to a warehouse system.
 * 3. Create posts from an external CRM.
 * 4. Build a mobile app powered by WordPress content.
 * 5. Build a custom live search feature.
 * 6. Create a headless WordPress site.
 * 7. Expose custom post types like Projects, Events, Properties, or Case Studies.
 * 8. Connect WordPress with marketing tools or reporting dashboards.
 *
 * In short:
 *
 * The REST API is the bridge between WordPress and other applications.
 */


/* ========================================================================== */
/* 19. WORDPRESS CODING STANDARDS                                             */
/* ========================================================================== */

/**
 * WordPress Coding Standards are a set of guidelines and best practices for
 * writing code that is consistent, readable, and maintainable within the
 * WordPress ecosystem.
 *
 * These standards cover several languages used across WordPress:
 * - PHP
 * - HTML
 * - CSS
 * - JavaScript
 *
 * The goal is to make code easy to understand, debug, and collaborate on,
 * regardless of who wrote it. When every theme, plugin, and core contribution
 * follows the same rules, a developer can open an unfamiliar file and still
 * read it comfortably, because the formatting and naming feel familiar.
 *
 * Why coding standards matter in practice:
 * - Consistency: every file "looks the same", so the team reads code faster.
 * - Readability: clear naming and spacing reduce misunderstandings.
 * - Maintainability: future developers (including your future self) can change
 *   the code safely.
 * - Collaboration: pull requests focus on logic, not on style arguments.
 * - Security: many standards (escaping, sanitizing, nonces) directly prevent
 *   common vulnerabilities.
 * - Fewer bugs: predictable patterns make mistakes easier to spot in review.
 *
 * Where the official standards live:
 * - The WordPress Developer Handbook documents the standards for PHP, HTML,
 *   CSS, JavaScript, and inline documentation.
 * - Historically, the WordPress core uses tabs for indentation (not spaces),
 *   Yoda conditions, and snake_case function names, which differ from many
 *   other PHP projects (such as PSR-12 / Laravel style).
 */


/* -------------------------------------------------------------------------- */
/* 19.1 THE FOUR STANDARD AREAS                                               */
/* -------------------------------------------------------------------------- */

/**
 * 1. PHP Coding Standards
 *    - Indent with tabs, not spaces.
 *    - Use snake_case for functions and variables: get_user_orders().
 *    - Use UPPER_SNAKE_CASE for constants: MY_PLUGIN_VERSION.
 *    - Always use full <?php ?> tags, never short tags like <? ?>.
 *    - Use Yoda conditions: if ( true === $is_active ) to avoid accidental
 *      assignment ( = ) instead of comparison ( == ).
 *    - Add spaces inside parentheses and around operators:
 *      foreach ( $items as $item ) { ... }
 *    - Escape on output, sanitize on input, and verify with nonces.
 *
 * 2. HTML Coding Standards
 *    - Use valid, well-formed markup.
 *    - Close all tags properly and use lowercase element/attribute names.
 *    - Indentation should reflect the nesting level.
 *
 * 3. CSS Coding Standards
 *    - One selector per line, lowercase hyphenated class names: .main-header.
 *    - A space before the opening brace and a semicolon after every value.
 *    - Group and comment sections so large stylesheets stay navigable.
 *
 * 4. JavaScript Coding Standards
 *    - Consistent spacing, semicolons, and camelCase variable names.
 *    - Prefer clear, descriptive names over abbreviations.
 *    - Avoid leaking variables into the global scope.
 */


/* -------------------------------------------------------------------------- */
/* 19.2 PHP NAMING AND STRUCTURE EXAMPLES                                     */
/* -------------------------------------------------------------------------- */

/**
 * Bad example (inconsistent, hard to maintain):
 */
/*
function GetUserOrders($ID){
$x=get_post_meta($ID,'orders',true);
if($x==''){return false;}
return $x;
}
*/

/**
 * Better example following WordPress standards:
 */
/*
function rocadev_get_user_orders( $user_id ) {
    $orders = get_user_meta( $user_id, 'orders', true );

    if ( '' === $orders ) {
        return false;
    }

    return $orders;
}
*/

/**
 * Notes on the improved version:
 * - Prefixed function name (rocadev_) avoids collisions with other plugins.
 * - snake_case naming.
 * - Spaces inside parentheses and around operators.
 * - Yoda condition: '' === $orders.
 * - Clear, descriptive variable names.
 */


/* -------------------------------------------------------------------------- */
/* 19.3 SECURITY-RELATED STANDARDS: ESCAPE, SANITIZE, VALIDATE                */
/* -------------------------------------------------------------------------- */

/**
 * A large part of WordPress coding standards is about handling data safely.
 *
 * Rule of thumb:
 * - Sanitize INPUT (data coming in).
 * - Validate INPUT (confirm it is the shape you expect).
 * - Escape OUTPUT (data going out to the browser).
 *
 * Common sanitizing functions:
 * - sanitize_text_field()
 * - sanitize_email()
 * - absint()
 * - wp_kses_post()
 *
 * Common escaping functions:
 * - esc_html()
 * - esc_attr()
 * - esc_url()
 * - esc_js()
 */

/*
$raw_name  = isset( $_POST['name'] ) ? $_POST['name'] : '';
$safe_name = sanitize_text_field( $raw_name );

echo '<p>Hello, ' . esc_html( $safe_name ) . '</p>';
*/


/* -------------------------------------------------------------------------- */
/* 19.4 TOOLS THAT ENFORCE THE STANDARDS                                      */
/* -------------------------------------------------------------------------- */

/**
 * You do not have to check every rule by hand. Tools can do it automatically.
 *
 * PHP_CodeSniffer (PHPCS) with WordPress Coding Standards (WPCS):
 * - PHPCS scans PHP files and reports violations.
 * - WPCS is a ruleset for PHPCS that knows the WordPress rules specifically.
 *
 * Typical setup uses Composer:
 *
 *   composer require --dev wp-coding-standards/wpcs
 *
 * Then run:
 *
 *   phpcs --standard=WordPress path/to/your/plugin
 *
 * And auto-fix what can be fixed automatically:
 *
 *   phpcbf --standard=WordPress path/to/your/plugin
 *
 * For JavaScript and CSS:
 * - ESLint and the @wordpress/eslint-plugin enforce JS standards.
 * - Stylelint with @wordpress/stylelint-config enforces CSS standards.
 *
 * Many of these are bundled in @wordpress/scripts, the official build tooling.
 *
 * Real-life use case:
 * Before opening a pull request, you run phpcbf to auto-format, then phpcs to
 * confirm there are no remaining issues. Reviewers can then focus on logic
 * instead of spacing, naming, and indentation.
 */


/* -------------------------------------------------------------------------- */
/* 19.5 INLINE DOCUMENTATION (PHPDoc) STANDARDS                               */
/* -------------------------------------------------------------------------- */

/**
 * WordPress also defines how to document code using DocBlocks.
 * Functions, classes, and hooks should describe what they do, their parameters,
 * and what they return.
 *
 * Example of a properly documented function:
 */
/*
/**
 * Get a formatted price for a product.
 *
 * @param int   $product_id The product ID.
 * @param array $args       Optional. Formatting options.
 * @return string The formatted price, or an empty string if not found.
 * /
function rocadev_get_formatted_price( $product_id, $args = array() ) {
    // ... implementation ...
    return '';
}
*/


/* -------------------------------------------------------------------------- */
/* 19.6 PRACTICAL CHECKLIST                                                   */
/* -------------------------------------------------------------------------- */

/**
 * A quick checklist you can apply to any WordPress PHP file:
 *
 * [ ] Prefix all functions, classes, and globals (e.g. rocadev_).
 * [ ] Use tabs for indentation.
 * [ ] Use snake_case for functions and variables.
 * [ ] Use Yoda conditions for comparisons.
 * [ ] Sanitize all input.
 * [ ] Validate input where a specific format is expected.
 * [ ] Escape all output (esc_html, esc_attr, esc_url).
 * [ ] Verify nonces for forms and AJAX/REST write actions.
 * [ ] Add DocBlocks to functions and classes.
 * [ ] Run phpcs / phpcbf with the WordPress standard before committing.
 *
 * See examples/coding-standards.php for a side-by-side "before and after"
 * file showing the same code written badly and then corrected to follow the
 * WordPress Coding Standards.
 */


/* ========================================================================== */
/* 20. THEMES IN DEPTH: CLASSIC THEMES AND BLOCK THEMES                        */
/* ========================================================================== */

/**
 * Section 4 introduced theme TYPES at a high level. This section zooms in on how
 * the two dominant approaches are actually built and customized:
 *
 *   - CLASSIC themes  -> PHP templates + functions.php (the "old" but still very
 *                        common way; most agency/legacy sites are classic).
 *   - BLOCK themes    -> templates made of blocks + a theme.json, edited visually
 *                        through Full Site Editing (FSE). The modern default since
 *                        WordPress 5.9 / the Twenty Twenty-Two theme.
 *
 * Mental model:
 *   Classic = "the theme is PHP code; the editor only edits CONTENT."
 *   Block   = "the theme is data (theme.json + block markup); the editor edits the
 *              CONTENT *and* the LAYOUT, header, footer, and styles."
 *
 * You will meet both in real projects, so know how each is structured.
 */


/* -------------------------------------------------------------------------- */
/* 20.1 CLASSIC THEMES — THEME STRUCTURE                                       */
/* -------------------------------------------------------------------------- */

/**
 * A classic theme is a folder in wp-content/themes/. Its required and common
 * building blocks:
 *
 * (a) style.css     - REQUIRED. Its header comment is the theme's identity card.
 *                     WordPress reads the metadata here to list the theme under
 *                     Appearance > Themes. (CSS rules can also live here, but most
 *                     real themes enqueue separate stylesheets — see section 8.)
 *
 * (b) functions.php - The theme's "bootstrap". Runs on every request. This is
 *                     where you declare theme supports, register menus and widget
 *                     areas, enqueue assets, and hook into WordPress. It behaves
 *                     like a plugin that is active only while this theme is.
 *
 * (c) Template Files - The PHP files that render pages: index.php, header.php,
 *                     footer.php, single.php, page.php, archive.php, 404.php, etc.
 *                     WordPress picks which one to use via the Template Hierarchy.
 *
 * (d) Child Themes  - A separate theme that inherits from a parent so you can
 *                     customize without losing changes on parent updates
 *                     (see 4.3 and 20.2 below).
 *
 * (e) Template Hierarchy - The deterministic set of rules WordPress follows to
 *                     decide which template file renders the current request.
 */

// (a) Example style.css header — the minimum metadata WordPress looks for.
/*
/*
Theme Name: Rocadev Classic
Theme URI: https://example.com/rocadev-classic
Author: Rocadev
Description: A lightweight classic starter theme.
Version: 1.0.0
Requires at least: 6.0
Requires PHP: 7.4
License: GPL-2.0-or-later
Text Domain: rocadev-classic
* /
*/

/**
 * (e) Template Hierarchy — how WordPress chooses a template (simplified).
 *
 * For a SINGLE BLOG POST, WordPress looks for the first file that exists:
 *   single-post-{slug}.php  ->  single-post.php  ->  single.php  ->  singular.php  ->  index.php
 *
 * For a PAGE:
 *   page-{slug}.php  ->  page-{id}.php  ->  page.php  ->  singular.php  ->  index.php
 *
 * For a CATEGORY archive:
 *   category-{slug}.php  ->  category-{id}.php  ->  category.php  ->  archive.php  ->  index.php
 *
 * For a CUSTOM POST TYPE single (e.g. 'case_study'):
 *   single-case_study.php  ->  single.php  ->  singular.php  ->  index.php
 *
 * index.php is the ultimate fallback and the ONLY strictly required template
 * (together with style.css) for a theme to be valid.
 *
 * Real-life use case:
 * Your "Case Studies" CPT (section 9) needs a different layout than blog posts.
 * You add single-case_study.php; WordPress automatically uses it for those URLs
 * without you writing any routing code.
 */

/**
 * See examples/classic-theme-setup.php for a working functions.php "theme setup":
 * theme supports (logo, title-tag, post-thumbnails), menu locations, a footer
 * widget area, and a Customizer setting — plus the header.php/footer.php template
 * tags that output them.
 */


/* -------------------------------------------------------------------------- */
/* 20.2 CLASSIC THEMES — CHILD THEMES (RECAP + WHY)                            */
/* -------------------------------------------------------------------------- */

/**
 * A child theme is a tiny theme whose style.css declares a "Template:" line
 * pointing at the parent. WordPress then loads the parent's templates/functions
 * and lets the child OVERRIDE any of them.
 *
 * Override rules:
 *   - Template files: a file in the child (e.g. single.php) REPLACES the parent's.
 *   - functions.php:  the child's runs IN ADDITION to the parent's (not replaced).
 *
 * Why it matters:
 *   Editing a third-party parent theme directly means your changes are wiped on
 *   the next update. A child theme keeps your code separate and update-safe.
 *
 * Minimum files: style.css (with the Template: header) + functions.php.
 * See 4.3 for the style.css header and the parent/child enqueue snippet.
 */


/* -------------------------------------------------------------------------- */
/* 20.3 CLASSIC THEMES — THEME CUSTOMIZATION                                   */
/* -------------------------------------------------------------------------- */

/**
 * "Theme customization" = the features that let a SITE OWNER (not a developer)
 * adjust the site, plus the developer tools that expose those options.
 *
 * MENUS
 *   The theme registers menu LOCATIONS with register_nav_menus(). The client then
 *   builds menus under Appearance > Menus and assigns them to a location. The
 *   template prints them with wp_nav_menu( array( 'theme_location' => 'primary' ) ).
 *
 * CUSTOMIZER (Appearance > Customize)
 *   A live-preview settings panel. Developers add sections/settings/controls via
 *   the Customizer API on the 'customize_register' hook. Values are read with
 *   get_theme_mod(). Every setting MUST have a sanitize_callback. Use
 *   'transport' => 'postMessage' + selective refresh to update the preview without
 *   a full reload. (Block themes replace much of this with the Site Editor.)
 *
 * WIDGETS
 *   Reusable blocks of content (search, recent posts, custom HTML) dropped into
 *   "widget areas" (a.k.a. sidebars). The theme registers an area with
 *   register_sidebar() and renders it with dynamic_sidebar( 'footer-1' ).
 *
 * TEMPLATE TAGS
 *   The PHP functions themes call to OUTPUT dynamic data inside templates:
 *   the_title(), the_content(), the_permalink(), the_post_thumbnail(),
 *   bloginfo(), wp_nav_menu(), dynamic_sidebar(), the_custom_logo(), etc.
 *   Most "the_*" tags echo directly; their "get_the_*" siblings return a value so
 *   you can escape/modify it before printing.
 *
 * CUSTOM FIELDS
 *   Extra per-post data ("post meta") beyond title/content — e.g. a subtitle,
 *   price, or client name. Stored in wp_postmeta as key/value pairs. Read with
 *   get_post_meta(); a metabox provides a friendly UI to edit them.
 *
 * ACF (Advanced Custom Fields)
 *   The most popular PLUGIN for custom fields. You define field groups in the
 *   admin (text, image, repeater, relationship, flexible content...) and read them
 *   in templates with get_field('name') / the_field('name'). It generates the same
 *   post-meta storage + metabox UI you would otherwise hand-code.
 *
 * METABOX
 *   Two meanings: (1) any box on the edit screen, added with add_meta_box(); and
 *   (2) "Meta Box" (metabox.io), a plugin similar in spirit to ACF. Hand-coding a
 *   metabox is the DIY alternative to ACF — you control the UI and the save logic
 *   (nonce + capability check + sanitize), which is exactly what ACF does for you.
 */

// Example: reading a Customizer value and a custom field inside a template.
/*
$phone = get_theme_mod( 'rocadev_phone', '' );
if ( '' !== $phone ) {
    echo '<a href="tel:' . esc_attr( $phone ) . '">' . esc_html( $phone ) . '</a>';
}

// Custom field (post meta). With ACF this would be: the_field('client_name');
$client = get_post_meta( get_the_ID(), '_rocadev_client_name', true );
echo esc_html( $client );
*/

/**
 * Examples for this subsection:
 *   - examples/classic-theme-setup.php  -> Menus, Widgets, Customizer, Template Tags.
 *   - examples/custom-metabox.php       -> Custom Fields via a hand-coded metabox
 *                                          (the manual version of what ACF/Metabox do),
 *                                          including nonce, capability check, sanitize,
 *                                          and escaped output.
 */


/* -------------------------------------------------------------------------- */
/* 20.4 BLOCK THEMES — OVERVIEW                                                */
/* -------------------------------------------------------------------------- */

/**
 * A block theme builds the ENTIRE site out of blocks and is edited visually
 * through Full Site Editing. Instead of PHP template files, templates are HTML
 * files containing block markup, and design tokens live in a single theme.json.
 *
 * Key differences from classic themes:
 *   - No PHP required for templates (though PHP/functions.php is still allowed).
 *   - The site owner can edit header, footer, and templates — not just content.
 *   - Colors/typography/spacing are declared once in theme.json and reused
 *     everywhere as CSS variables.
 */


/* -------------------------------------------------------------------------- */
/* 20.5 BLOCK THEMES — THEME STRUCTURE                                         */
/* -------------------------------------------------------------------------- */

/**
 * A minimal block theme folder looks like:
 *
 *   your-theme/
 *   |- style.css            (still required, for the header metadata)
 *   |- theme.json           (settings + default styles; the design "brain")
 *   |- templates/
 *   |   |- index.html       (required fallback, block markup)
 *   |   |- single.html
 *   |   |- page.html
 *   |   `- archive.html
 *   |- parts/
 *   |   |- header.html      (a Template Part)
 *   |   `- footer.html      (a Template Part)
 *   |- patterns/            (file-based block patterns, auto-registered)
 *   `- functions.php        (OPTIONAL: enqueue extra assets, register patterns, etc.)
 *
 * The Template Hierarchy still applies, but with .html files in /templates/
 * instead of .php files in the theme root.
 */


/* -------------------------------------------------------------------------- */
/* 20.6 BLOCK THEMES — FULL SITE EDITING (FSE)                                 */
/* -------------------------------------------------------------------------- */

/**
 * Full Site Editing is the experience at Appearance > Editor. With a block theme
 * active, the site owner can visually edit:
 *   - Templates (single, page, archive, 404...) and Template Parts (header/footer).
 *   - Global Styles (colors, typography, spacing) layered on top of theme.json.
 *   - Navigation, via the Navigation block.
 *
 * How edits are stored:
 *   theme.json and the theme's .html files are the DEFAULTS shipped by the theme.
 *   When a user edits in the Site Editor, WordPress saves the override to the
 *   DATABASE (as wp_template / wp_template_part / wp_global_styles posts). The
 *   theme files are never modified. "Clear customizations" reverts to the theme
 *   defaults — this is the "Overrides" idea in 20.10.
 */


/* -------------------------------------------------------------------------- */
/* 20.7 BLOCK THEMES — TEMPLATE PARTS                                          */
/* -------------------------------------------------------------------------- */

/**
 * A Template Part is a reusable chunk of block markup — most commonly the header
 * and the footer — stored in /parts/ and declared in theme.json under
 * "templateParts" with an "area" (header | footer | uncategorized).
 *
 * Templates include a part with the Template Part block:
 *   <!-- wp:template-part {"slug":"header","area":"header"} /-->
 *
 * This is the block-theme equivalent of classic get_header() / get_footer():
 * define the header once, reuse it across every template, and let the owner edit
 * it in one place from the Site Editor.
 */


/* -------------------------------------------------------------------------- */
/* 20.8 BLOCK THEMES — BLOCK PATTERNS                                          */
/* -------------------------------------------------------------------------- */

/**
 * A block pattern is a pre-designed arrangement of blocks (hero, CTA, pricing,
 * testimonials) the user inserts with one click and then edits freely. Patterns
 * give clients consistent, on-brand sections without rebuilding layouts each time.
 *
 * Two ways to provide patterns:
 *   - File-based (preferred for themes): a PHP file in /patterns/ with a header
 *     comment; WordPress auto-registers it. No hooks needed.
 *   - Code-based: register_block_pattern() + register_block_pattern_category(),
 *     useful in plugins or for dynamically generated patterns.
 *
 * Patterns can also be pulled from the wordpress.org Pattern Directory.
 *
 * See examples/block-patterns.php for both approaches (a full-width "Call to
 * action" pattern registered in code, plus the file-based equivalent).
 */


/* -------------------------------------------------------------------------- */
/* 20.9 BLOCK THEMES — STYLES (theme.json + GLOBAL STYLES + VARIATIONS)        */
/* -------------------------------------------------------------------------- */

/**
 * theme.json is the heart of a block theme's design system. It has two main keys:
 *
 *   "settings" - what the editor is ALLOWED to do and the presets users can pick:
 *                color palette, font sizes, spacing scale, layout content/wide
 *                widths, whether custom colors are permitted, etc. Each preset
 *                becomes a CSS variable, e.g. --wp--preset--color--brand.
 *
 *   "styles"   - the DEFAULT appearance built from those presets: page background
 *                and text color, base typography, and per-element / per-block
 *                styles (links, buttons, headings, core/quote, ...).
 *
 * Benefits:
 *   - One source of truth: change the brand color once, it updates everywhere.
 *   - Consistent options: the editor only offers the palette you defined.
 *   - Less custom CSS: most styling is data, not stylesheets.
 *
 * STYLE VARIATIONS
 *   Alternate full-theme looks (e.g. "Light", "Dark", "High contrast") shipped as
 *   JSON files in /styles/. The user switches between them in the Site Editor with
 *   one click. Each file mirrors the theme.json "settings"/"styles" shape.
 *
 * See examples/block-theme-theme-json.json for a commented, realistic theme.json
 * (palette, fluid typography, spacing scale, element/block styles, template parts).
 */


/* -------------------------------------------------------------------------- */
/* 20.10 BLOCK THEMES — OVERRIDES                                              */
/* -------------------------------------------------------------------------- */

/**
 * "Overrides" appears in two related places in the block world:
 *
 * (1) USER OVERRIDES OF THE THEME (Site Editor)
 *     Theme files (theme.json, templates, parts) are defaults. Edits made in the
 *     Site Editor are stored in the DATABASE and take precedence over the theme.
 *     A "Clear customizations" / "Reset" action discards the database copy and
 *     falls back to the theme's shipped version. Knowing this is essential when a
 *     client says "my header changes won't go away after I updated the theme" —
 *     the database override is winning over the theme file.
 *
 * (2) PATTERN / SYNCED-PATTERN OVERRIDES (block "bindings")
 *     A synced pattern (formerly "reusable block") normally shows identical
 *     content everywhere. With the Overrides feature, specific blocks inside a
 *     synced pattern can be marked overridable, so each insertion keeps the shared
 *     DESIGN but allows unique CONTENT (e.g. a shared "team member card" layout
 *     with a different name/photo per page). This is powered by the Block Bindings
 *     API under the hood.
 *
 * Mental model:
 *   Theme files = defaults  ->  database (Site Editor) = overrides  ->  what renders.
 */


/* -------------------------------------------------------------------------- */
/* 20.11 CLASSIC vs BLOCK — QUICK COMPARISON                                   */
/* -------------------------------------------------------------------------- */

/**
 * | Concern              | Classic theme                 | Block theme                  |
 * |----------------------|-------------------------------|------------------------------|
 * | Templates            | PHP files (single.php...)     | HTML block files (single.html)|
 * | Header/footer        | get_header() / get_footer()   | Template Parts               |
 * | Global design tokens | CSS + functions.php           | theme.json                   |
 * | Owner edits layout?  | No (content only)             | Yes (Full Site Editing)      |
 * | Site-wide settings   | Customizer API                | Site Editor + Global Styles  |
 * | Reusable sections    | template parts / includes     | Block Patterns               |
 * | Custom fields        | Metabox / ACF                 | Metabox / ACF (still work)   |
 *
 * Which to choose:
 *   - New build, design flexibility for the client -> block theme (modern default).
 *   - Maintaining an existing PHP/page-builder site -> classic theme.
 *   - Hybrid themes (4.4) let a classic base adopt block-editor content gradually.
 */

